/*
 * This file was auto-generated by speedy-antlr-tool v1.1.0
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#pragma once

#include "Java9_v2BaseVisitor.h"
#include "speedy_antlr.h"

class SA_Java9_v2Translator : public Java9_v2BaseVisitor {
    speedy_antlr::Translator *translator;

    // Cached context classes
    PyObject *LiteralContext_cls = NULL;
    PyObject *PrimitiveType1Context_cls = NULL;
    PyObject *PrimitiveType2Context_cls = NULL;
    PyObject *NumericType1Context_cls = NULL;
    PyObject *NumericType2Context_cls = NULL;
    PyObject *IntegralTypeContext_cls = NULL;
    PyObject *FloatingPointTypeContext_cls = NULL;
    PyObject *ReferenceType3Context_cls = NULL;
    PyObject *ReferenceType2Context_cls = NULL;
    PyObject *ReferenceType1Context_cls = NULL;
    PyObject *ClassOrInterfaceTypeContext_cls = NULL;
    PyObject *ClassType1Context_cls = NULL;
    PyObject *ClassType2Context_cls = NULL;
    PyObject *ClassType_lf_classOrInterfaceTypeContext_cls = NULL;
    PyObject *ClassType_lfno_classOrInterfaceTypeContext_cls = NULL;
    PyObject *InterfaceTypeContext_cls = NULL;
    PyObject *InterfaceType_lf_classOrInterfaceTypeContext_cls = NULL;
    PyObject *InterfaceType_lfno_classOrInterfaceTypeContext_cls = NULL;
    PyObject *TypeVariableContext_cls = NULL;
    PyObject *ArrayTyp3Context_cls = NULL;
    PyObject *ArrayType1Context_cls = NULL;
    PyObject *ArrayType2Context_cls = NULL;
    PyObject *DimsContext_cls = NULL;
    PyObject *TypeParameterContext_cls = NULL;
    PyObject *TypeParameterModifierContext_cls = NULL;
    PyObject *TypeBound2Context_cls = NULL;
    PyObject *TypeBound1Context_cls = NULL;
    PyObject *AdditionalBoundContext_cls = NULL;
    PyObject *TypeArgumentsContext_cls = NULL;
    PyObject *TypeArgumentListContext_cls = NULL;
    PyObject *TypeArgument1Context_cls = NULL;
    PyObject *TypeArgument2Context_cls = NULL;
    PyObject *WildcardContext_cls = NULL;
    PyObject *WildcardBound2Context_cls = NULL;
    PyObject *WildcardBounds1Context_cls = NULL;
    PyObject *ModuleName1Context_cls = NULL;
    PyObject *ModuleName2Context_cls = NULL;
    PyObject *PackageName2Context_cls = NULL;
    PyObject *PackageName1Context_cls = NULL;
    PyObject *TypeName1Context_cls = NULL;
    PyObject *TypeName2Context_cls = NULL;
    PyObject *PackageOrTypeName1Context_cls = NULL;
    PyObject *PackageOrTypeName2Context_cls = NULL;
    PyObject *ExpressionName2Context_cls = NULL;
    PyObject *ExpressionName1Context_cls = NULL;
    PyObject *MethodNameContext_cls = NULL;
    PyObject *AmbiguousName1Context_cls = NULL;
    PyObject *AmbiguousName2Context_cls = NULL;
    PyObject *CompilationUnit2Context_cls = NULL;
    PyObject *CompilationUnit1Context_cls = NULL;
    PyObject *OrdinaryCompilationContext_cls = NULL;
    PyObject *ModularCompilationContext_cls = NULL;
    PyObject *PackageDeclarationContext_cls = NULL;
    PyObject *PackageModifierContext_cls = NULL;
    PyObject *ImportDeclaration3Context_cls = NULL;
    PyObject *ImportDeclaration4Context_cls = NULL;
    PyObject *ImportDeclaration1Context_cls = NULL;
    PyObject *ImportDeclaration2Context_cls = NULL;
    PyObject *SingleTypeImportDeclarationContext_cls = NULL;
    PyObject *TypeImportOnDemandDeclarationContext_cls = NULL;
    PyObject *SingleStaticImportDeclarationContext_cls = NULL;
    PyObject *StaticImportOnDemandDeclarationContext_cls = NULL;
    PyObject *TypeDeclaration2Context_cls = NULL;
    PyObject *TypeDeclaration3Context_cls = NULL;
    PyObject *TypeDeclaration1Context_cls = NULL;
    PyObject *ModuleDeclarationContext_cls = NULL;
    PyObject *ModuleDirective5Context_cls = NULL;
    PyObject *ModuleDirective4Context_cls = NULL;
    PyObject *ModuleDirective1Context_cls = NULL;
    PyObject *ModuleDirective2Context_cls = NULL;
    PyObject *ModuleDirectiv3Context_cls = NULL;
    PyObject *RequiresModifierContext_cls = NULL;
    PyObject *ClassDeclaration1Context_cls = NULL;
    PyObject *ClassDeclaration2Context_cls = NULL;
    PyObject *NormalClassDeclarationContext_cls = NULL;
    PyObject *ClassModifierContext_cls = NULL;
    PyObject *TypeParametersContext_cls = NULL;
    PyObject *TypeParameterListContext_cls = NULL;
    PyObject *SuperclassContext_cls = NULL;
    PyObject *SuperinterfacesContext_cls = NULL;
    PyObject *InterfaceTypeListContext_cls = NULL;
    PyObject *ClassBodyContext_cls = NULL;
    PyObject *ClassBodyDeclaration4Context_cls = NULL;
    PyObject *ClassBodyDeclaration1Context_cls = NULL;
    PyObject *ClassBodyDeclaration3Context_cls = NULL;
    PyObject *ClassBodyDeclaration2Context_cls = NULL;
    PyObject *ClassMemberDeclaration4Context_cls = NULL;
    PyObject *ClassMemberDeclaration5Context_cls = NULL;
    PyObject *ClassMemberDeclaration2Context_cls = NULL;
    PyObject *ClassMemberDeclaration3Context_cls = NULL;
    PyObject *ClassMemberDeclaration1Context_cls = NULL;
    PyObject *FieldDeclarationContext_cls = NULL;
    PyObject *FieldModifierContext_cls = NULL;
    PyObject *VariableDeclaratorListContext_cls = NULL;
    PyObject *VariableDeclaratorContext_cls = NULL;
    PyObject *VariableDeclaratorIdContext_cls = NULL;
    PyObject *VariableInitializer1Context_cls = NULL;
    PyObject *VariableInitializer2Context_cls = NULL;
    PyObject *UnannType2Context_cls = NULL;
    PyObject *UnannType1Context_cls = NULL;
    PyObject *UnannPrimitiveType2Context_cls = NULL;
    PyObject *UnannPrimitiveType1Context_cls = NULL;
    PyObject *UnannReferenceType3Context_cls = NULL;
    PyObject *UnannReferenceType1Context_cls = NULL;
    PyObject *UnannReferenceType2Context_cls = NULL;
    PyObject *UnannClassOrInterfaceTypeContext_cls = NULL;
    PyObject *UnannClassType2Context_cls = NULL;
    PyObject *UnannClassType1Context_cls = NULL;
    PyObject *UnannClassType_lf_unannClassOrInterfaceTypeContext_cls = NULL;
    PyObject *UnannClassType_lfno_unannClassOrInterfaceTypeContext_cls = NULL;
    PyObject *UnannInterfaceTypeContext_cls = NULL;
    PyObject *UnannInterfaceType_lf_unannClassOrInterfaceTypeContext_cls = NULL;
    PyObject *UnannInterfaceType_lfno_unannClassOrInterfaceTypeContext_cls = NULL;
    PyObject *UnannTypeVariableContext_cls = NULL;
    PyObject *UnannArrayType2Context_cls = NULL;
    PyObject *UnannArrayType1Context_cls = NULL;
    PyObject *UnannArrayTyp3Context_cls = NULL;
    PyObject *MethodDeclarationContext_cls = NULL;
    PyObject *MethodModifierContext_cls = NULL;
    PyObject *MethodHeaderContext_cls = NULL;
    PyObject *ResultContext_cls = NULL;
    PyObject *MethodDeclaratorContext_cls = NULL;
    PyObject *FormalParameterList3Context_cls = NULL;
    PyObject *FormalParameterList2Context_cls = NULL;
    PyObject *FormalParameterList1Context_cls = NULL;
    PyObject *FormalParameters2Context_cls = NULL;
    PyObject *FormalParameters1Context_cls = NULL;
    PyObject *FormalParameterContext_cls = NULL;
    PyObject *VariableModifierContext_cls = NULL;
    PyObject *LastFormalParameter2Context_cls = NULL;
    PyObject *LastFormalParameter1Context_cls = NULL;
    PyObject *ReceiverParameterContext_cls = NULL;
    PyObject *Throws_Context_cls = NULL;
    PyObject *ExceptionTypeListContext_cls = NULL;
    PyObject *ExceptionType2Context_cls = NULL;
    PyObject *ExceptionType1Context_cls = NULL;
    PyObject *MethodBodyContext_cls = NULL;
    PyObject *InstanceInitializerContext_cls = NULL;
    PyObject *StaticInitializerContext_cls = NULL;
    PyObject *ConstructorDeclarationContext_cls = NULL;
    PyObject *ConstructorModifierContext_cls = NULL;
    PyObject *ConstructorDeclaratorContext_cls = NULL;
    PyObject *SimpleTypeNameContext_cls = NULL;
    PyObject *ConstructorBodyContext_cls = NULL;
    PyObject *ExplicitConstructorInvocation1Context_cls = NULL;
    PyObject *ExplicitConstructorInvocation4Context_cls = NULL;
    PyObject *ExplicitConstructorInvocation2Context_cls = NULL;
    PyObject *ExplicitConstructorInvocation3Context_cls = NULL;
    PyObject *EnumDeclarationContext_cls = NULL;
    PyObject *EnumBodyContext_cls = NULL;
    PyObject *EnumConstantListContext_cls = NULL;
    PyObject *EnumConstantContext_cls = NULL;
    PyObject *EnumConstantModifierContext_cls = NULL;
    PyObject *EnumBodyDeclarationsContext_cls = NULL;
    PyObject *InterfaceDeclaration1Context_cls = NULL;
    PyObject *InterfaceDeclaration2Context_cls = NULL;
    PyObject *NormalInterfaceDeclarationContext_cls = NULL;
    PyObject *InterfaceModifierContext_cls = NULL;
    PyObject *ExtendsInterfacesContext_cls = NULL;
    PyObject *InterfaceBodyContext_cls = NULL;
    PyObject *InterfaceMemberDeclaration5Context_cls = NULL;
    PyObject *InterfaceMemberDeclaration4Context_cls = NULL;
    PyObject *InterfaceMemberDeclaration3Context_cls = NULL;
    PyObject *InterfaceMemberDeclaration2Context_cls = NULL;
    PyObject *InterfaceMemberDeclaration1Context_cls = NULL;
    PyObject *ConstantDeclarationContext_cls = NULL;
    PyObject *ConstantModifierContext_cls = NULL;
    PyObject *InterfaceMethodDeclarationContext_cls = NULL;
    PyObject *InterfaceMethodModifierContext_cls = NULL;
    PyObject *AnnotationTypeDeclarationContext_cls = NULL;
    PyObject *AnnotationTypeBodyContext_cls = NULL;
    PyObject *AnnotationTypeMemberDeclaration1Context_cls = NULL;
    PyObject *AnnotationTypeMemberDeclaration2Context_cls = NULL;
    PyObject *AnnotationTypeMemberDeclaration3Context_cls = NULL;
    PyObject *AnnotationTypeMemberDeclaration4Context_cls = NULL;
    PyObject *AnnotationTypeMemberDeclaration5Context_cls = NULL;
    PyObject *AnnotationTypeElementDeclarationContext_cls = NULL;
    PyObject *AnnotationTypeElementModifierContext_cls = NULL;
    PyObject *DefaultValueContext_cls = NULL;
    PyObject *Annotation3Context_cls = NULL;
    PyObject *Annotation2Context_cls = NULL;
    PyObject *Annotation1Context_cls = NULL;
    PyObject *NormalAnnotationContext_cls = NULL;
    PyObject *ElementValuePairListContext_cls = NULL;
    PyObject *ElementValuePairContext_cls = NULL;
    PyObject *ElementValue2Context_cls = NULL;
    PyObject *ElementValue1Context_cls = NULL;
    PyObject *ElementValu3Context_cls = NULL;
    PyObject *ElementValueArrayInitializerContext_cls = NULL;
    PyObject *ElementValueListContext_cls = NULL;
    PyObject *MarkerAnnotationContext_cls = NULL;
    PyObject *SingleElementAnnotationContext_cls = NULL;
    PyObject *ArrayInitializerContext_cls = NULL;
    PyObject *VariableInitializerListContext_cls = NULL;
    PyObject *BlockContext_cls = NULL;
    PyObject *BlockStatementsContext_cls = NULL;
    PyObject *BlockStatement1Context_cls = NULL;
    PyObject *BlockStatement3Context_cls = NULL;
    PyObject *BlockStatement2Context_cls = NULL;
    PyObject *LocalVariableDeclarationStatementContext_cls = NULL;
    PyObject *LocalVariableDeclarationContext_cls = NULL;
    PyObject *Statement5Context_cls = NULL;
    PyObject *Statement6Context_cls = NULL;
    PyObject *Statement3Context_cls = NULL;
    PyObject *Statement4Context_cls = NULL;
    PyObject *Statement1Context_cls = NULL;
    PyObject *Statement2Context_cls = NULL;
    PyObject *StatementNoShortIf5Context_cls = NULL;
    PyObject *StatementNoShortIf2Context_cls = NULL;
    PyObject *StatementNoShortIf1Context_cls = NULL;
    PyObject *StatementNoShortIf4Context_cls = NULL;
    PyObject *StatementNoShortIf3Context_cls = NULL;
    PyObject *StatementWithoutTrailingSubstatement8Context_cls = NULL;
    PyObject *StatementWithoutTrailingSubstatement9Context_cls = NULL;
    PyObject *StatementWithoutTrailingSubstatement4Context_cls = NULL;
    PyObject *StatementWithoutTrailingSubstatement5Context_cls = NULL;
    PyObject *StatementWithoutTrailingSubstatement6Context_cls = NULL;
    PyObject *StatementWithoutTrailingSubstatement7Context_cls = NULL;
    PyObject *StatementWithoutTrailingSubstatement1Context_cls = NULL;
    PyObject *StatementWithoutTrailingSubstatement10Context_cls = NULL;
    PyObject *StatementWithoutTrailingSubstatement2Context_cls = NULL;
    PyObject *StatementWithoutTrailingSubstatement3Context_cls = NULL;
    PyObject *StatementWithoutTrailingSubstatement11Context_cls = NULL;
    PyObject *StatementWithoutTrailingSubstatement12Context_cls = NULL;
    PyObject *EmptyStatementContext_cls = NULL;
    PyObject *LabeledStatementContext_cls = NULL;
    PyObject *LabeledStatementNoShortIfContext_cls = NULL;
    PyObject *ExpressionStatementContext_cls = NULL;
    PyObject *StatementExpression3Context_cls = NULL;
    PyObject *StatementExpression4Context_cls = NULL;
    PyObject *StatementExpression5Context_cls = NULL;
    PyObject *StatementExpression6Context_cls = NULL;
    PyObject *StatementExpression1Context_cls = NULL;
    PyObject *StatementExpression2Context_cls = NULL;
    PyObject *StatementExpression7Context_cls = NULL;
    PyObject *IfThenStatementContext_cls = NULL;
    PyObject *IfThenElseStatementContext_cls = NULL;
    PyObject *IfThenElseStatementNoShortIfContext_cls = NULL;
    PyObject *AssertStatement2Context_cls = NULL;
    PyObject *AssertStatement1Context_cls = NULL;
    PyObject *SwitchStatementContext_cls = NULL;
    PyObject *SwitchBlockContext_cls = NULL;
    PyObject *SwitchBlockStatementGroupContext_cls = NULL;
    PyObject *SwitchLabelsContext_cls = NULL;
    PyObject *SwitchLabel3Context_cls = NULL;
    PyObject *SwitchLabel2Context_cls = NULL;
    PyObject *SwitchLabel1Context_cls = NULL;
    PyObject *EnumConstantNameContext_cls = NULL;
    PyObject *WhileStatementContext_cls = NULL;
    PyObject *WhileStatementNoShortIfContext_cls = NULL;
    PyObject *DoStatementContext_cls = NULL;
    PyObject *ForStatement1Context_cls = NULL;
    PyObject *ForStatement2Context_cls = NULL;
    PyObject *ForStatementNoShortIf3Context_cls = NULL;
    PyObject *ForStatementNoShortIf4Context_cls = NULL;
    PyObject *BasicForStatementContext_cls = NULL;
    PyObject *BasicForStatementNoShortIfContext_cls = NULL;
    PyObject *ForInit1Context_cls = NULL;
    PyObject *ForInit2Context_cls = NULL;
    PyObject *ForUpdateContext_cls = NULL;
    PyObject *StatementExpressionListContext_cls = NULL;
    PyObject *EnhancedForStatementContext_cls = NULL;
    PyObject *EnhancedForStatementNoShortIfContext_cls = NULL;
    PyObject *BreakStatementContext_cls = NULL;
    PyObject *ContinueStatementContext_cls = NULL;
    PyObject *ReturnStatementContext_cls = NULL;
    PyObject *ThrowStatementContext_cls = NULL;
    PyObject *SynchronizedStatementContext_cls = NULL;
    PyObject *TryStatement2Context_cls = NULL;
    PyObject *TryStatement3Context_cls = NULL;
    PyObject *TryStatement1Context_cls = NULL;
    PyObject *CatchesContext_cls = NULL;
    PyObject *CatchClauseContext_cls = NULL;
    PyObject *CatchFormalParameterContext_cls = NULL;
    PyObject *CatchTypeContext_cls = NULL;
    PyObject *Finally_Context_cls = NULL;
    PyObject *TryWithResourcesStatementContext_cls = NULL;
    PyObject *ResourceSpecificationContext_cls = NULL;
    PyObject *ResourceListContext_cls = NULL;
    PyObject *Resource2Context_cls = NULL;
    PyObject *Resource1Context_cls = NULL;
    PyObject *VariableAccess1Context_cls = NULL;
    PyObject *VariableAccess2Context_cls = NULL;
    PyObject *PrimaryContext_cls = NULL;
    PyObject *PrimaryNoNewArray1Context_cls = NULL;
    PyObject *PrimaryNoNewArray2Context_cls = NULL;
    PyObject *PrimaryNoNewArray3Context_cls = NULL;
    PyObject *PrimaryNoNewArray8Context_cls = NULL;
    PyObject *PrimaryNoNewArray9Context_cls = NULL;
    PyObject *PrimaryNoNewArray4Context_cls = NULL;
    PyObject *PrimaryNoNewArray5Context_cls = NULL;
    PyObject *PrimaryNoNewArray6Context_cls = NULL;
    PyObject *PrimaryNoNewArray10Context_cls = NULL;
    PyObject *PrimaryNoNewArray7Context_cls = NULL;
    PyObject *PrimaryNoNewArray_lf_arrayAccessContext_cls = NULL;
    PyObject *PrimaryNoNewArray_lfno_arrayAccess6Context_cls = NULL;
    PyObject *PrimaryNoNewArray_lfno_arrayAccess10Context_cls = NULL;
    PyObject *PrimaryNoNewArray_lfno_arrayAccess7Context_cls = NULL;
    PyObject *PrimaryNoNewArray_lfno_arrayAccess4Context_cls = NULL;
    PyObject *PrimaryNoNewArray_lfno_arrayAccess5Context_cls = NULL;
    PyObject *PrimaryNoNewArray_lfno_arrayAccess8Context_cls = NULL;
    PyObject *PrimaryNoNewArray_lfno_arrayAccess9Context_cls = NULL;
    PyObject *PrimaryNoNewArray_lfno_arrayAccess2Context_cls = NULL;
    PyObject *PrimaryNoNewArray_lfno_arrayAccess3Context_cls = NULL;
    PyObject *PrimaryNoNewArray_lfno_arrayAccess1Context_cls = NULL;
    PyObject *PrimaryNoNewArray_lf_primary2Context_cls = NULL;
    PyObject *PrimaryNoNewArray_lf_primary3Context_cls = NULL;
    PyObject *PrimaryNoNewArray_lf_primary1Context_cls = NULL;
    PyObject *PrimaryNoNewArray_lf_primary4Context_cls = NULL;
    PyObject *PrimaryNoNewArray_lf_primary5Context_cls = NULL;
    PyObject *PrimaryNoNewArray_lf_primary_lf_arrayAccess_lf_primaryContext_cls = NULL;
    PyObject *PrimaryNoNewArray_lf_primary_lfno_arrayAccess_lf_primary1Context_cls = NULL;
    PyObject *PrimaryNoNewArray_lf_primary_lfno_arrayAccess_lf_primary3Context_cls = NULL;
    PyObject *PrimaryNoNewArray_lf_primary_lfno_arrayAccess_lf_primary2Context_cls = NULL;
    PyObject *PrimaryNoNewArray_lf_primary_lfno_arrayAccess_lf_primary4Context_cls = NULL;
    PyObject *PrimaryNoNewArray_lfno_primary9Context_cls = NULL;
    PyObject *PrimaryNoNewArray_lfno_primary5Context_cls = NULL;
    PyObject *PrimaryNoNewArray_lfno_primary6Context_cls = NULL;
    PyObject *PrimaryNoNewArray_lfno_primary7Context_cls = NULL;
    PyObject *PrimaryNoNewArray_lfno_primary8Context_cls = NULL;
    PyObject *PrimaryNoNewArray_lfno_primary1Context_cls = NULL;
    PyObject *PrimaryNoNewArray_lfno_primary2Context_cls = NULL;
    PyObject *PrimaryNoNewArray_lfno_primary12Context_cls = NULL;
    PyObject *PrimaryNoNewArray_lfno_primary3Context_cls = NULL;
    PyObject *PrimaryNoNewArray_lfno_primary11Context_cls = NULL;
    PyObject *PrimaryNoNewArray_lfno_primary4Context_cls = NULL;
    PyObject *PrimaryNoNewArray_lfno_primary10Context_cls = NULL;
    PyObject *PrimaryNoNewArray_lfno_primary_lf_arrayAccess_lfno_primaryContext_cls = NULL;
    PyObject *PrimaryNoNewArray_lfno_primary_lfno_arrayAccess_lfno_primary3Context_cls = NULL;
    PyObject *PrimaryNoNewArray_lfno_primary_lfno_arrayAccess_lfno_primary11Context_cls = NULL;
    PyObject *PrimaryNoNewArray_lfno_primary_lfno_arrayAccess_lfno_primary2Context_cls = NULL;
    PyObject *PrimaryNoNewArray_lfno_primary_lfno_arrayAccess_lfno_primary5Context_cls = NULL;
    PyObject *PrimaryNoNewArray_lfno_primary_lfno_arrayAccess_lfno_primary4Context_cls = NULL;
    PyObject *PrimaryNoNewArray_lfno_primary_lfno_arrayAccess_lfno_primary10Context_cls = NULL;
    PyObject *PrimaryNoNewArray_lfno_primary_lfno_arrayAccess_lfno_primary1Context_cls = NULL;
    PyObject *PrimaryNoNewArray_lfno_primary_lfno_arrayAccess_lfno_primary7Context_cls = NULL;
    PyObject *PrimaryNoNewArray_lfno_primary_lfno_arrayAccess_lfno_primary6Context_cls = NULL;
    PyObject *PrimaryNoNewArray_lfno_primary_lfno_arrayAccess_lfno_primary9Context_cls = NULL;
    PyObject *PrimaryNoNewArray_lfno_primary_lfno_arrayAccess_lfno_primary8Context_cls = NULL;
    PyObject *ClassLiteral2Context_cls = NULL;
    PyObject *ClassLiteral1Context_cls = NULL;
    PyObject *ClassInstanceCreationExpression1Context_cls = NULL;
    PyObject *ClassInstanceCreationExpression3Context_cls = NULL;
    PyObject *ClassInstanceCreationExpression2Context_cls = NULL;
    PyObject *ClassInstanceCreationExpression_lf_primaryContext_cls = NULL;
    PyObject *ClassInstanceCreationExpression_lfno_primary1Context_cls = NULL;
    PyObject *ClassInstanceCreationExpression_lfno_primary2Context_cls = NULL;
    PyObject *TypeArgumentsOrDiamond1Context_cls = NULL;
    PyObject *TypeArgumentsOrDiamond2Context_cls = NULL;
    PyObject *FieldAccess1Context_cls = NULL;
    PyObject *FieldAccess2Context_cls = NULL;
    PyObject *FieldAccess3Context_cls = NULL;
    PyObject *FieldAccess_lf_primaryContext_cls = NULL;
    PyObject *FieldAccess_lfno_primary2Context_cls = NULL;
    PyObject *FieldAccess_lfno_primary1Context_cls = NULL;
    PyObject *ArrayAccessContext_cls = NULL;
    PyObject *ArrayAccess_lf_primaryContext_cls = NULL;
    PyObject *ArrayAccess_lfno_primaryContext_cls = NULL;
    PyObject *MethodInvocation1Context_cls = NULL;
    PyObject *MethodInvocation2Context_cls = NULL;
    PyObject *MethodInvocation3Context_cls = NULL;
    PyObject *MethodInvocation4Context_cls = NULL;
    PyObject *MethodInvocation5Context_cls = NULL;
    PyObject *MethodInvocation6Context_cls = NULL;
    PyObject *MethodInvocation_lf_primaryContext_cls = NULL;
    PyObject *MethodInvocation_lfno_primary3Context_cls = NULL;
    PyObject *MethodInvocation_lfno_primary2Context_cls = NULL;
    PyObject *MethodInvocation_lfno_primary1Context_cls = NULL;
    PyObject *MethodInvocation_lfno_primary5Context_cls = NULL;
    PyObject *MethodInvocation_lfno_primary4Context_cls = NULL;
    PyObject *ArgumentListContext_cls = NULL;
    PyObject *MethodReference1Context_cls = NULL;
    PyObject *MethodReference3Context_cls = NULL;
    PyObject *MethodReference2Context_cls = NULL;
    PyObject *MethodReference5Context_cls = NULL;
    PyObject *MethodReference4Context_cls = NULL;
    PyObject *MethodReference7Context_cls = NULL;
    PyObject *MethodReference6Context_cls = NULL;
    PyObject *MethodReference_lf_primaryContext_cls = NULL;
    PyObject *MethodReference_lfno_primary6Context_cls = NULL;
    PyObject *MethodReference_lfno_primary5Context_cls = NULL;
    PyObject *MethodReference_lfno_primary4Context_cls = NULL;
    PyObject *MethodReference_lfno_primary3Context_cls = NULL;
    PyObject *MethodReference_lfno_primary2Context_cls = NULL;
    PyObject *MethodReference_lfno_primary1Context_cls = NULL;
    PyObject *ArrayCreationExpression4Context_cls = NULL;
    PyObject *ArrayCreationExpression2Context_cls = NULL;
    PyObject *ArrayCreationExpression3Context_cls = NULL;
    PyObject *ArrayCreationExpression1Context_cls = NULL;
    PyObject *DimExprsContext_cls = NULL;
    PyObject *DimExprContext_cls = NULL;
    PyObject *ConstantExpressionContext_cls = NULL;
    PyObject *Expression2Context_cls = NULL;
    PyObject *Expression1Context_cls = NULL;
    PyObject *LambdaExpressionContext_cls = NULL;
    PyObject *LambdaParameters3Context_cls = NULL;
    PyObject *LambdaParameters1Context_cls = NULL;
    PyObject *LambdaParameters2Context_cls = NULL;
    PyObject *InferredFormalParameterListContext_cls = NULL;
    PyObject *LambdaBody1Context_cls = NULL;
    PyObject *LambdaBody2Context_cls = NULL;
    PyObject *AssignmentExpression1Context_cls = NULL;
    PyObject *AssignmentExpression2Context_cls = NULL;
    PyObject *AssignmentContext_cls = NULL;
    PyObject *LeftHandSide5Context_cls = NULL;
    PyObject *LeftHandSide4Context_cls = NULL;
    PyObject *LeftHandSide3Context_cls = NULL;
    PyObject *AssignmentOperatorContext_cls = NULL;
    PyObject *ConditionalExpression1Context_cls = NULL;
    PyObject *ConditionalExpression2Context_cls = NULL;
    PyObject *ConditionalOrExpression1Context_cls = NULL;
    PyObject *ConditionalOrExpression2Context_cls = NULL;
    PyObject *ConditionalAndExpression2Context_cls = NULL;
    PyObject *ConditionalAndExpression1Context_cls = NULL;
    PyObject *InclusiveOrExpression2Context_cls = NULL;
    PyObject *InclusiveOrExpression1Context_cls = NULL;
    PyObject *ExclusiveOrExpression1Context_cls = NULL;
    PyObject *ExclusiveOrExpression2Context_cls = NULL;
    PyObject *AndExpression2Context_cls = NULL;
    PyObject *AndExpression1Context_cls = NULL;
    PyObject *EqualityExpression3Context_cls = NULL;
    PyObject *EqualityExpression2Context_cls = NULL;
    PyObject *EqualityExpression1Context_cls = NULL;
    PyObject *RelationalExpression1Context_cls = NULL;
    PyObject *RelationalExpression2Context_cls = NULL;
    PyObject *RelationalExpression5Context_cls = NULL;
    PyObject *RelationalExpression6Context_cls = NULL;
    PyObject *RelationalExpression3Context_cls = NULL;
    PyObject *RelationalExpression4Context_cls = NULL;
    PyObject *ShiftExpression1Context_cls = NULL;
    PyObject *ShiftExpression3Context_cls = NULL;
    PyObject *ShiftExpression2Context_cls = NULL;
    PyObject *ShiftExpression4Context_cls = NULL;
    PyObject *AdditiveExpression1Context_cls = NULL;
    PyObject *AdditiveExpression3Context_cls = NULL;
    PyObject *AdditiveExpressio2Context_cls = NULL;
    PyObject *MultiplicativeExpression1Context_cls = NULL;
    PyObject *MultiplicativeExpression4Context_cls = NULL;
    PyObject *MultiplicativeExpression3Context_cls = NULL;
    PyObject *MultiplicativeExpression2Context_cls = NULL;
    PyObject *UnaryExpression2Context_cls = NULL;
    PyObject *UnaryExpression1Context_cls = NULL;
    PyObject *UnaryExpression5Context_cls = NULL;
    PyObject *UnaryExpression4Context_cls = NULL;
    PyObject *UnaryExpression3Context_cls = NULL;
    PyObject *PreIncrementExpressionContext_cls = NULL;
    PyObject *PreDecrementExpressionContext_cls = NULL;
    PyObject *UnaryExpressionNotPlusMinus4Context_cls = NULL;
    PyObject *UnaryExpressionNotPlusMinus3Context_cls = NULL;
    PyObject *UnaryExpressionNotPlusMinus2Context_cls = NULL;
    PyObject *UnaryExpressionNotPlusMinus1Context_cls = NULL;
    PyObject *PostfixExpressionContext_cls = NULL;
    PyObject *PostIncrementExpressionContext_cls = NULL;
    PyObject *PostIncrementExpression_lf_postfixExpressionContext_cls = NULL;
    PyObject *PostDecrementExpressionContext_cls = NULL;
    PyObject *PostDecrementExpression_lf_postfixExpressionContext_cls = NULL;
    PyObject *CastExpression3Context_cls = NULL;
    PyObject *CastExpression1Context_cls = NULL;
    PyObject *CastExpression2Context_cls = NULL;
    PyObject *IdentifierContext_cls = NULL;

    public:
    SA_Java9_v2Translator(speedy_antlr::Translator *translator);
    ~SA_Java9_v2Translator();
    antlrcpp::Any visitLiteral(Java9_v2Parser::LiteralContext *ctx);

    antlrcpp::Any visitPrimitiveType1(Java9_v2Parser::PrimitiveType1Context *ctx);

    antlrcpp::Any visitPrimitiveType2(Java9_v2Parser::PrimitiveType2Context *ctx);

    antlrcpp::Any visitNumericType1(Java9_v2Parser::NumericType1Context *ctx);

    antlrcpp::Any visitNumericType2(Java9_v2Parser::NumericType2Context *ctx);

    antlrcpp::Any visitIntegralType(Java9_v2Parser::IntegralTypeContext *ctx);

    antlrcpp::Any visitFloatingPointType(Java9_v2Parser::FloatingPointTypeContext *ctx);

    antlrcpp::Any visitReferenceType3(Java9_v2Parser::ReferenceType3Context *ctx);

    antlrcpp::Any visitReferenceType2(Java9_v2Parser::ReferenceType2Context *ctx);

    antlrcpp::Any visitReferenceType1(Java9_v2Parser::ReferenceType1Context *ctx);

    antlrcpp::Any visitClassOrInterfaceType(Java9_v2Parser::ClassOrInterfaceTypeContext *ctx);

    antlrcpp::Any visitClassType1(Java9_v2Parser::ClassType1Context *ctx);

    antlrcpp::Any visitClassType2(Java9_v2Parser::ClassType2Context *ctx);

    antlrcpp::Any visitClassType_lf_classOrInterfaceType(Java9_v2Parser::ClassType_lf_classOrInterfaceTypeContext *ctx);

    antlrcpp::Any visitClassType_lfno_classOrInterfaceType(Java9_v2Parser::ClassType_lfno_classOrInterfaceTypeContext *ctx);

    antlrcpp::Any visitInterfaceType(Java9_v2Parser::InterfaceTypeContext *ctx);

    antlrcpp::Any visitInterfaceType_lf_classOrInterfaceType(Java9_v2Parser::InterfaceType_lf_classOrInterfaceTypeContext *ctx);

    antlrcpp::Any visitInterfaceType_lfno_classOrInterfaceType(Java9_v2Parser::InterfaceType_lfno_classOrInterfaceTypeContext *ctx);

    antlrcpp::Any visitTypeVariable(Java9_v2Parser::TypeVariableContext *ctx);

    antlrcpp::Any visitArrayTyp3(Java9_v2Parser::ArrayTyp3Context *ctx);

    antlrcpp::Any visitArrayType1(Java9_v2Parser::ArrayType1Context *ctx);

    antlrcpp::Any visitArrayType2(Java9_v2Parser::ArrayType2Context *ctx);

    antlrcpp::Any visitDims(Java9_v2Parser::DimsContext *ctx);

    antlrcpp::Any visitTypeParameter(Java9_v2Parser::TypeParameterContext *ctx);

    antlrcpp::Any visitTypeParameterModifier(Java9_v2Parser::TypeParameterModifierContext *ctx);

    antlrcpp::Any visitTypeBound2(Java9_v2Parser::TypeBound2Context *ctx);

    antlrcpp::Any visitTypeBound1(Java9_v2Parser::TypeBound1Context *ctx);

    antlrcpp::Any visitAdditionalBound(Java9_v2Parser::AdditionalBoundContext *ctx);

    antlrcpp::Any visitTypeArguments(Java9_v2Parser::TypeArgumentsContext *ctx);

    antlrcpp::Any visitTypeArgumentList(Java9_v2Parser::TypeArgumentListContext *ctx);

    antlrcpp::Any visitTypeArgument1(Java9_v2Parser::TypeArgument1Context *ctx);

    antlrcpp::Any visitTypeArgument2(Java9_v2Parser::TypeArgument2Context *ctx);

    antlrcpp::Any visitWildcard(Java9_v2Parser::WildcardContext *ctx);

    antlrcpp::Any visitWildcardBound2(Java9_v2Parser::WildcardBound2Context *ctx);

    antlrcpp::Any visitWildcardBounds1(Java9_v2Parser::WildcardBounds1Context *ctx);

    antlrcpp::Any visitModuleName1(Java9_v2Parser::ModuleName1Context *ctx);

    antlrcpp::Any visitModuleName2(Java9_v2Parser::ModuleName2Context *ctx);

    antlrcpp::Any visitPackageName2(Java9_v2Parser::PackageName2Context *ctx);

    antlrcpp::Any visitPackageName1(Java9_v2Parser::PackageName1Context *ctx);

    antlrcpp::Any visitTypeName1(Java9_v2Parser::TypeName1Context *ctx);

    antlrcpp::Any visitTypeName2(Java9_v2Parser::TypeName2Context *ctx);

    antlrcpp::Any visitPackageOrTypeName1(Java9_v2Parser::PackageOrTypeName1Context *ctx);

    antlrcpp::Any visitPackageOrTypeName2(Java9_v2Parser::PackageOrTypeName2Context *ctx);

    antlrcpp::Any visitExpressionName2(Java9_v2Parser::ExpressionName2Context *ctx);

    antlrcpp::Any visitExpressionName1(Java9_v2Parser::ExpressionName1Context *ctx);

    antlrcpp::Any visitMethodName(Java9_v2Parser::MethodNameContext *ctx);

    antlrcpp::Any visitAmbiguousName1(Java9_v2Parser::AmbiguousName1Context *ctx);

    antlrcpp::Any visitAmbiguousName2(Java9_v2Parser::AmbiguousName2Context *ctx);

    antlrcpp::Any visitCompilationUnit2(Java9_v2Parser::CompilationUnit2Context *ctx);

    antlrcpp::Any visitCompilationUnit1(Java9_v2Parser::CompilationUnit1Context *ctx);

    antlrcpp::Any visitOrdinaryCompilation(Java9_v2Parser::OrdinaryCompilationContext *ctx);

    antlrcpp::Any visitModularCompilation(Java9_v2Parser::ModularCompilationContext *ctx);

    antlrcpp::Any visitPackageDeclaration(Java9_v2Parser::PackageDeclarationContext *ctx);

    antlrcpp::Any visitPackageModifier(Java9_v2Parser::PackageModifierContext *ctx);

    antlrcpp::Any visitImportDeclaration3(Java9_v2Parser::ImportDeclaration3Context *ctx);

    antlrcpp::Any visitImportDeclaration4(Java9_v2Parser::ImportDeclaration4Context *ctx);

    antlrcpp::Any visitImportDeclaration1(Java9_v2Parser::ImportDeclaration1Context *ctx);

    antlrcpp::Any visitImportDeclaration2(Java9_v2Parser::ImportDeclaration2Context *ctx);

    antlrcpp::Any visitSingleTypeImportDeclaration(Java9_v2Parser::SingleTypeImportDeclarationContext *ctx);

    antlrcpp::Any visitTypeImportOnDemandDeclaration(Java9_v2Parser::TypeImportOnDemandDeclarationContext *ctx);

    antlrcpp::Any visitSingleStaticImportDeclaration(Java9_v2Parser::SingleStaticImportDeclarationContext *ctx);

    antlrcpp::Any visitStaticImportOnDemandDeclaration(Java9_v2Parser::StaticImportOnDemandDeclarationContext *ctx);

    antlrcpp::Any visitTypeDeclaration2(Java9_v2Parser::TypeDeclaration2Context *ctx);

    antlrcpp::Any visitTypeDeclaration3(Java9_v2Parser::TypeDeclaration3Context *ctx);

    antlrcpp::Any visitTypeDeclaration1(Java9_v2Parser::TypeDeclaration1Context *ctx);

    antlrcpp::Any visitModuleDeclaration(Java9_v2Parser::ModuleDeclarationContext *ctx);

    antlrcpp::Any visitModuleDirective5(Java9_v2Parser::ModuleDirective5Context *ctx);

    antlrcpp::Any visitModuleDirective4(Java9_v2Parser::ModuleDirective4Context *ctx);

    antlrcpp::Any visitModuleDirective1(Java9_v2Parser::ModuleDirective1Context *ctx);

    antlrcpp::Any visitModuleDirective2(Java9_v2Parser::ModuleDirective2Context *ctx);

    antlrcpp::Any visitModuleDirectiv3(Java9_v2Parser::ModuleDirectiv3Context *ctx);

    antlrcpp::Any visitRequiresModifier(Java9_v2Parser::RequiresModifierContext *ctx);

    antlrcpp::Any visitClassDeclaration1(Java9_v2Parser::ClassDeclaration1Context *ctx);

    antlrcpp::Any visitClassDeclaration2(Java9_v2Parser::ClassDeclaration2Context *ctx);

    antlrcpp::Any visitNormalClassDeclaration(Java9_v2Parser::NormalClassDeclarationContext *ctx);

    antlrcpp::Any visitClassModifier(Java9_v2Parser::ClassModifierContext *ctx);

    antlrcpp::Any visitTypeParameters(Java9_v2Parser::TypeParametersContext *ctx);

    antlrcpp::Any visitTypeParameterList(Java9_v2Parser::TypeParameterListContext *ctx);

    antlrcpp::Any visitSuperclass(Java9_v2Parser::SuperclassContext *ctx);

    antlrcpp::Any visitSuperinterfaces(Java9_v2Parser::SuperinterfacesContext *ctx);

    antlrcpp::Any visitInterfaceTypeList(Java9_v2Parser::InterfaceTypeListContext *ctx);

    antlrcpp::Any visitClassBody(Java9_v2Parser::ClassBodyContext *ctx);

    antlrcpp::Any visitClassBodyDeclaration4(Java9_v2Parser::ClassBodyDeclaration4Context *ctx);

    antlrcpp::Any visitClassBodyDeclaration1(Java9_v2Parser::ClassBodyDeclaration1Context *ctx);

    antlrcpp::Any visitClassBodyDeclaration3(Java9_v2Parser::ClassBodyDeclaration3Context *ctx);

    antlrcpp::Any visitClassBodyDeclaration2(Java9_v2Parser::ClassBodyDeclaration2Context *ctx);

    antlrcpp::Any visitClassMemberDeclaration4(Java9_v2Parser::ClassMemberDeclaration4Context *ctx);

    antlrcpp::Any visitClassMemberDeclaration5(Java9_v2Parser::ClassMemberDeclaration5Context *ctx);

    antlrcpp::Any visitClassMemberDeclaration2(Java9_v2Parser::ClassMemberDeclaration2Context *ctx);

    antlrcpp::Any visitClassMemberDeclaration3(Java9_v2Parser::ClassMemberDeclaration3Context *ctx);

    antlrcpp::Any visitClassMemberDeclaration1(Java9_v2Parser::ClassMemberDeclaration1Context *ctx);

    antlrcpp::Any visitFieldDeclaration(Java9_v2Parser::FieldDeclarationContext *ctx);

    antlrcpp::Any visitFieldModifier(Java9_v2Parser::FieldModifierContext *ctx);

    antlrcpp::Any visitVariableDeclaratorList(Java9_v2Parser::VariableDeclaratorListContext *ctx);

    antlrcpp::Any visitVariableDeclarator(Java9_v2Parser::VariableDeclaratorContext *ctx);

    antlrcpp::Any visitVariableDeclaratorId(Java9_v2Parser::VariableDeclaratorIdContext *ctx);

    antlrcpp::Any visitVariableInitializer1(Java9_v2Parser::VariableInitializer1Context *ctx);

    antlrcpp::Any visitVariableInitializer2(Java9_v2Parser::VariableInitializer2Context *ctx);

    antlrcpp::Any visitUnannType2(Java9_v2Parser::UnannType2Context *ctx);

    antlrcpp::Any visitUnannType1(Java9_v2Parser::UnannType1Context *ctx);

    antlrcpp::Any visitUnannPrimitiveType2(Java9_v2Parser::UnannPrimitiveType2Context *ctx);

    antlrcpp::Any visitUnannPrimitiveType1(Java9_v2Parser::UnannPrimitiveType1Context *ctx);

    antlrcpp::Any visitUnannReferenceType3(Java9_v2Parser::UnannReferenceType3Context *ctx);

    antlrcpp::Any visitUnannReferenceType1(Java9_v2Parser::UnannReferenceType1Context *ctx);

    antlrcpp::Any visitUnannReferenceType2(Java9_v2Parser::UnannReferenceType2Context *ctx);

    antlrcpp::Any visitUnannClassOrInterfaceType(Java9_v2Parser::UnannClassOrInterfaceTypeContext *ctx);

    antlrcpp::Any visitUnannClassType2(Java9_v2Parser::UnannClassType2Context *ctx);

    antlrcpp::Any visitUnannClassType1(Java9_v2Parser::UnannClassType1Context *ctx);

    antlrcpp::Any visitUnannClassType_lf_unannClassOrInterfaceType(Java9_v2Parser::UnannClassType_lf_unannClassOrInterfaceTypeContext *ctx);

    antlrcpp::Any visitUnannClassType_lfno_unannClassOrInterfaceType(Java9_v2Parser::UnannClassType_lfno_unannClassOrInterfaceTypeContext *ctx);

    antlrcpp::Any visitUnannInterfaceType(Java9_v2Parser::UnannInterfaceTypeContext *ctx);

    antlrcpp::Any visitUnannInterfaceType_lf_unannClassOrInterfaceType(Java9_v2Parser::UnannInterfaceType_lf_unannClassOrInterfaceTypeContext *ctx);

    antlrcpp::Any visitUnannInterfaceType_lfno_unannClassOrInterfaceType(Java9_v2Parser::UnannInterfaceType_lfno_unannClassOrInterfaceTypeContext *ctx);

    antlrcpp::Any visitUnannTypeVariable(Java9_v2Parser::UnannTypeVariableContext *ctx);

    antlrcpp::Any visitUnannArrayType2(Java9_v2Parser::UnannArrayType2Context *ctx);

    antlrcpp::Any visitUnannArrayType1(Java9_v2Parser::UnannArrayType1Context *ctx);

    antlrcpp::Any visitUnannArrayTyp3(Java9_v2Parser::UnannArrayTyp3Context *ctx);

    antlrcpp::Any visitMethodDeclaration(Java9_v2Parser::MethodDeclarationContext *ctx);

    antlrcpp::Any visitMethodModifier(Java9_v2Parser::MethodModifierContext *ctx);

    antlrcpp::Any visitMethodHeader(Java9_v2Parser::MethodHeaderContext *ctx);

    antlrcpp::Any visitResult(Java9_v2Parser::ResultContext *ctx);

    antlrcpp::Any visitMethodDeclarator(Java9_v2Parser::MethodDeclaratorContext *ctx);

    antlrcpp::Any visitFormalParameterList3(Java9_v2Parser::FormalParameterList3Context *ctx);

    antlrcpp::Any visitFormalParameterList2(Java9_v2Parser::FormalParameterList2Context *ctx);

    antlrcpp::Any visitFormalParameterList1(Java9_v2Parser::FormalParameterList1Context *ctx);

    antlrcpp::Any visitFormalParameters2(Java9_v2Parser::FormalParameters2Context *ctx);

    antlrcpp::Any visitFormalParameters1(Java9_v2Parser::FormalParameters1Context *ctx);

    antlrcpp::Any visitFormalParameter(Java9_v2Parser::FormalParameterContext *ctx);

    antlrcpp::Any visitVariableModifier(Java9_v2Parser::VariableModifierContext *ctx);

    antlrcpp::Any visitLastFormalParameter2(Java9_v2Parser::LastFormalParameter2Context *ctx);

    antlrcpp::Any visitLastFormalParameter1(Java9_v2Parser::LastFormalParameter1Context *ctx);

    antlrcpp::Any visitReceiverParameter(Java9_v2Parser::ReceiverParameterContext *ctx);

    antlrcpp::Any visitThrows_(Java9_v2Parser::Throws_Context *ctx);

    antlrcpp::Any visitExceptionTypeList(Java9_v2Parser::ExceptionTypeListContext *ctx);

    antlrcpp::Any visitExceptionType2(Java9_v2Parser::ExceptionType2Context *ctx);

    antlrcpp::Any visitExceptionType1(Java9_v2Parser::ExceptionType1Context *ctx);

    antlrcpp::Any visitMethodBody(Java9_v2Parser::MethodBodyContext *ctx);

    antlrcpp::Any visitInstanceInitializer(Java9_v2Parser::InstanceInitializerContext *ctx);

    antlrcpp::Any visitStaticInitializer(Java9_v2Parser::StaticInitializerContext *ctx);

    antlrcpp::Any visitConstructorDeclaration(Java9_v2Parser::ConstructorDeclarationContext *ctx);

    antlrcpp::Any visitConstructorModifier(Java9_v2Parser::ConstructorModifierContext *ctx);

    antlrcpp::Any visitConstructorDeclarator(Java9_v2Parser::ConstructorDeclaratorContext *ctx);

    antlrcpp::Any visitSimpleTypeName(Java9_v2Parser::SimpleTypeNameContext *ctx);

    antlrcpp::Any visitConstructorBody(Java9_v2Parser::ConstructorBodyContext *ctx);

    antlrcpp::Any visitExplicitConstructorInvocation1(Java9_v2Parser::ExplicitConstructorInvocation1Context *ctx);

    antlrcpp::Any visitExplicitConstructorInvocation4(Java9_v2Parser::ExplicitConstructorInvocation4Context *ctx);

    antlrcpp::Any visitExplicitConstructorInvocation2(Java9_v2Parser::ExplicitConstructorInvocation2Context *ctx);

    antlrcpp::Any visitExplicitConstructorInvocation3(Java9_v2Parser::ExplicitConstructorInvocation3Context *ctx);

    antlrcpp::Any visitEnumDeclaration(Java9_v2Parser::EnumDeclarationContext *ctx);

    antlrcpp::Any visitEnumBody(Java9_v2Parser::EnumBodyContext *ctx);

    antlrcpp::Any visitEnumConstantList(Java9_v2Parser::EnumConstantListContext *ctx);

    antlrcpp::Any visitEnumConstant(Java9_v2Parser::EnumConstantContext *ctx);

    antlrcpp::Any visitEnumConstantModifier(Java9_v2Parser::EnumConstantModifierContext *ctx);

    antlrcpp::Any visitEnumBodyDeclarations(Java9_v2Parser::EnumBodyDeclarationsContext *ctx);

    antlrcpp::Any visitInterfaceDeclaration1(Java9_v2Parser::InterfaceDeclaration1Context *ctx);

    antlrcpp::Any visitInterfaceDeclaration2(Java9_v2Parser::InterfaceDeclaration2Context *ctx);

    antlrcpp::Any visitNormalInterfaceDeclaration(Java9_v2Parser::NormalInterfaceDeclarationContext *ctx);

    antlrcpp::Any visitInterfaceModifier(Java9_v2Parser::InterfaceModifierContext *ctx);

    antlrcpp::Any visitExtendsInterfaces(Java9_v2Parser::ExtendsInterfacesContext *ctx);

    antlrcpp::Any visitInterfaceBody(Java9_v2Parser::InterfaceBodyContext *ctx);

    antlrcpp::Any visitInterfaceMemberDeclaration5(Java9_v2Parser::InterfaceMemberDeclaration5Context *ctx);

    antlrcpp::Any visitInterfaceMemberDeclaration4(Java9_v2Parser::InterfaceMemberDeclaration4Context *ctx);

    antlrcpp::Any visitInterfaceMemberDeclaration3(Java9_v2Parser::InterfaceMemberDeclaration3Context *ctx);

    antlrcpp::Any visitInterfaceMemberDeclaration2(Java9_v2Parser::InterfaceMemberDeclaration2Context *ctx);

    antlrcpp::Any visitInterfaceMemberDeclaration1(Java9_v2Parser::InterfaceMemberDeclaration1Context *ctx);

    antlrcpp::Any visitConstantDeclaration(Java9_v2Parser::ConstantDeclarationContext *ctx);

    antlrcpp::Any visitConstantModifier(Java9_v2Parser::ConstantModifierContext *ctx);

    antlrcpp::Any visitInterfaceMethodDeclaration(Java9_v2Parser::InterfaceMethodDeclarationContext *ctx);

    antlrcpp::Any visitInterfaceMethodModifier(Java9_v2Parser::InterfaceMethodModifierContext *ctx);

    antlrcpp::Any visitAnnotationTypeDeclaration(Java9_v2Parser::AnnotationTypeDeclarationContext *ctx);

    antlrcpp::Any visitAnnotationTypeBody(Java9_v2Parser::AnnotationTypeBodyContext *ctx);

    antlrcpp::Any visitAnnotationTypeMemberDeclaration1(Java9_v2Parser::AnnotationTypeMemberDeclaration1Context *ctx);

    antlrcpp::Any visitAnnotationTypeMemberDeclaration2(Java9_v2Parser::AnnotationTypeMemberDeclaration2Context *ctx);

    antlrcpp::Any visitAnnotationTypeMemberDeclaration3(Java9_v2Parser::AnnotationTypeMemberDeclaration3Context *ctx);

    antlrcpp::Any visitAnnotationTypeMemberDeclaration4(Java9_v2Parser::AnnotationTypeMemberDeclaration4Context *ctx);

    antlrcpp::Any visitAnnotationTypeMemberDeclaration5(Java9_v2Parser::AnnotationTypeMemberDeclaration5Context *ctx);

    antlrcpp::Any visitAnnotationTypeElementDeclaration(Java9_v2Parser::AnnotationTypeElementDeclarationContext *ctx);

    antlrcpp::Any visitAnnotationTypeElementModifier(Java9_v2Parser::AnnotationTypeElementModifierContext *ctx);

    antlrcpp::Any visitDefaultValue(Java9_v2Parser::DefaultValueContext *ctx);

    antlrcpp::Any visitAnnotation3(Java9_v2Parser::Annotation3Context *ctx);

    antlrcpp::Any visitAnnotation2(Java9_v2Parser::Annotation2Context *ctx);

    antlrcpp::Any visitAnnotation1(Java9_v2Parser::Annotation1Context *ctx);

    antlrcpp::Any visitNormalAnnotation(Java9_v2Parser::NormalAnnotationContext *ctx);

    antlrcpp::Any visitElementValuePairList(Java9_v2Parser::ElementValuePairListContext *ctx);

    antlrcpp::Any visitElementValuePair(Java9_v2Parser::ElementValuePairContext *ctx);

    antlrcpp::Any visitElementValue2(Java9_v2Parser::ElementValue2Context *ctx);

    antlrcpp::Any visitElementValue1(Java9_v2Parser::ElementValue1Context *ctx);

    antlrcpp::Any visitElementValu3(Java9_v2Parser::ElementValu3Context *ctx);

    antlrcpp::Any visitElementValueArrayInitializer(Java9_v2Parser::ElementValueArrayInitializerContext *ctx);

    antlrcpp::Any visitElementValueList(Java9_v2Parser::ElementValueListContext *ctx);

    antlrcpp::Any visitMarkerAnnotation(Java9_v2Parser::MarkerAnnotationContext *ctx);

    antlrcpp::Any visitSingleElementAnnotation(Java9_v2Parser::SingleElementAnnotationContext *ctx);

    antlrcpp::Any visitArrayInitializer(Java9_v2Parser::ArrayInitializerContext *ctx);

    antlrcpp::Any visitVariableInitializerList(Java9_v2Parser::VariableInitializerListContext *ctx);

    antlrcpp::Any visitBlock(Java9_v2Parser::BlockContext *ctx);

    antlrcpp::Any visitBlockStatements(Java9_v2Parser::BlockStatementsContext *ctx);

    antlrcpp::Any visitBlockStatement1(Java9_v2Parser::BlockStatement1Context *ctx);

    antlrcpp::Any visitBlockStatement3(Java9_v2Parser::BlockStatement3Context *ctx);

    antlrcpp::Any visitBlockStatement2(Java9_v2Parser::BlockStatement2Context *ctx);

    antlrcpp::Any visitLocalVariableDeclarationStatement(Java9_v2Parser::LocalVariableDeclarationStatementContext *ctx);

    antlrcpp::Any visitLocalVariableDeclaration(Java9_v2Parser::LocalVariableDeclarationContext *ctx);

    antlrcpp::Any visitStatement5(Java9_v2Parser::Statement5Context *ctx);

    antlrcpp::Any visitStatement6(Java9_v2Parser::Statement6Context *ctx);

    antlrcpp::Any visitStatement3(Java9_v2Parser::Statement3Context *ctx);

    antlrcpp::Any visitStatement4(Java9_v2Parser::Statement4Context *ctx);

    antlrcpp::Any visitStatement1(Java9_v2Parser::Statement1Context *ctx);

    antlrcpp::Any visitStatement2(Java9_v2Parser::Statement2Context *ctx);

    antlrcpp::Any visitStatementNoShortIf5(Java9_v2Parser::StatementNoShortIf5Context *ctx);

    antlrcpp::Any visitStatementNoShortIf2(Java9_v2Parser::StatementNoShortIf2Context *ctx);

    antlrcpp::Any visitStatementNoShortIf1(Java9_v2Parser::StatementNoShortIf1Context *ctx);

    antlrcpp::Any visitStatementNoShortIf4(Java9_v2Parser::StatementNoShortIf4Context *ctx);

    antlrcpp::Any visitStatementNoShortIf3(Java9_v2Parser::StatementNoShortIf3Context *ctx);

    antlrcpp::Any visitStatementWithoutTrailingSubstatement8(Java9_v2Parser::StatementWithoutTrailingSubstatement8Context *ctx);

    antlrcpp::Any visitStatementWithoutTrailingSubstatement9(Java9_v2Parser::StatementWithoutTrailingSubstatement9Context *ctx);

    antlrcpp::Any visitStatementWithoutTrailingSubstatement4(Java9_v2Parser::StatementWithoutTrailingSubstatement4Context *ctx);

    antlrcpp::Any visitStatementWithoutTrailingSubstatement5(Java9_v2Parser::StatementWithoutTrailingSubstatement5Context *ctx);

    antlrcpp::Any visitStatementWithoutTrailingSubstatement6(Java9_v2Parser::StatementWithoutTrailingSubstatement6Context *ctx);

    antlrcpp::Any visitStatementWithoutTrailingSubstatement7(Java9_v2Parser::StatementWithoutTrailingSubstatement7Context *ctx);

    antlrcpp::Any visitStatementWithoutTrailingSubstatement1(Java9_v2Parser::StatementWithoutTrailingSubstatement1Context *ctx);

    antlrcpp::Any visitStatementWithoutTrailingSubstatement10(Java9_v2Parser::StatementWithoutTrailingSubstatement10Context *ctx);

    antlrcpp::Any visitStatementWithoutTrailingSubstatement2(Java9_v2Parser::StatementWithoutTrailingSubstatement2Context *ctx);

    antlrcpp::Any visitStatementWithoutTrailingSubstatement3(Java9_v2Parser::StatementWithoutTrailingSubstatement3Context *ctx);

    antlrcpp::Any visitStatementWithoutTrailingSubstatement11(Java9_v2Parser::StatementWithoutTrailingSubstatement11Context *ctx);

    antlrcpp::Any visitStatementWithoutTrailingSubstatement12(Java9_v2Parser::StatementWithoutTrailingSubstatement12Context *ctx);

    antlrcpp::Any visitEmptyStatement(Java9_v2Parser::EmptyStatementContext *ctx);

    antlrcpp::Any visitLabeledStatement(Java9_v2Parser::LabeledStatementContext *ctx);

    antlrcpp::Any visitLabeledStatementNoShortIf(Java9_v2Parser::LabeledStatementNoShortIfContext *ctx);

    antlrcpp::Any visitExpressionStatement(Java9_v2Parser::ExpressionStatementContext *ctx);

    antlrcpp::Any visitStatementExpression3(Java9_v2Parser::StatementExpression3Context *ctx);

    antlrcpp::Any visitStatementExpression4(Java9_v2Parser::StatementExpression4Context *ctx);

    antlrcpp::Any visitStatementExpression5(Java9_v2Parser::StatementExpression5Context *ctx);

    antlrcpp::Any visitStatementExpression6(Java9_v2Parser::StatementExpression6Context *ctx);

    antlrcpp::Any visitStatementExpression1(Java9_v2Parser::StatementExpression1Context *ctx);

    antlrcpp::Any visitStatementExpression2(Java9_v2Parser::StatementExpression2Context *ctx);

    antlrcpp::Any visitStatementExpression7(Java9_v2Parser::StatementExpression7Context *ctx);

    antlrcpp::Any visitIfThenStatement(Java9_v2Parser::IfThenStatementContext *ctx);

    antlrcpp::Any visitIfThenElseStatement(Java9_v2Parser::IfThenElseStatementContext *ctx);

    antlrcpp::Any visitIfThenElseStatementNoShortIf(Java9_v2Parser::IfThenElseStatementNoShortIfContext *ctx);

    antlrcpp::Any visitAssertStatement2(Java9_v2Parser::AssertStatement2Context *ctx);

    antlrcpp::Any visitAssertStatement1(Java9_v2Parser::AssertStatement1Context *ctx);

    antlrcpp::Any visitSwitchStatement(Java9_v2Parser::SwitchStatementContext *ctx);

    antlrcpp::Any visitSwitchBlock(Java9_v2Parser::SwitchBlockContext *ctx);

    antlrcpp::Any visitSwitchBlockStatementGroup(Java9_v2Parser::SwitchBlockStatementGroupContext *ctx);

    antlrcpp::Any visitSwitchLabels(Java9_v2Parser::SwitchLabelsContext *ctx);

    antlrcpp::Any visitSwitchLabel3(Java9_v2Parser::SwitchLabel3Context *ctx);

    antlrcpp::Any visitSwitchLabel2(Java9_v2Parser::SwitchLabel2Context *ctx);

    antlrcpp::Any visitSwitchLabel1(Java9_v2Parser::SwitchLabel1Context *ctx);

    antlrcpp::Any visitEnumConstantName(Java9_v2Parser::EnumConstantNameContext *ctx);

    antlrcpp::Any visitWhileStatement(Java9_v2Parser::WhileStatementContext *ctx);

    antlrcpp::Any visitWhileStatementNoShortIf(Java9_v2Parser::WhileStatementNoShortIfContext *ctx);

    antlrcpp::Any visitDoStatement(Java9_v2Parser::DoStatementContext *ctx);

    antlrcpp::Any visitForStatement1(Java9_v2Parser::ForStatement1Context *ctx);

    antlrcpp::Any visitForStatement2(Java9_v2Parser::ForStatement2Context *ctx);

    antlrcpp::Any visitForStatementNoShortIf3(Java9_v2Parser::ForStatementNoShortIf3Context *ctx);

    antlrcpp::Any visitForStatementNoShortIf4(Java9_v2Parser::ForStatementNoShortIf4Context *ctx);

    antlrcpp::Any visitBasicForStatement(Java9_v2Parser::BasicForStatementContext *ctx);

    antlrcpp::Any visitBasicForStatementNoShortIf(Java9_v2Parser::BasicForStatementNoShortIfContext *ctx);

    antlrcpp::Any visitForInit1(Java9_v2Parser::ForInit1Context *ctx);

    antlrcpp::Any visitForInit2(Java9_v2Parser::ForInit2Context *ctx);

    antlrcpp::Any visitForUpdate(Java9_v2Parser::ForUpdateContext *ctx);

    antlrcpp::Any visitStatementExpressionList(Java9_v2Parser::StatementExpressionListContext *ctx);

    antlrcpp::Any visitEnhancedForStatement(Java9_v2Parser::EnhancedForStatementContext *ctx);

    antlrcpp::Any visitEnhancedForStatementNoShortIf(Java9_v2Parser::EnhancedForStatementNoShortIfContext *ctx);

    antlrcpp::Any visitBreakStatement(Java9_v2Parser::BreakStatementContext *ctx);

    antlrcpp::Any visitContinueStatement(Java9_v2Parser::ContinueStatementContext *ctx);

    antlrcpp::Any visitReturnStatement(Java9_v2Parser::ReturnStatementContext *ctx);

    antlrcpp::Any visitThrowStatement(Java9_v2Parser::ThrowStatementContext *ctx);

    antlrcpp::Any visitSynchronizedStatement(Java9_v2Parser::SynchronizedStatementContext *ctx);

    antlrcpp::Any visitTryStatement2(Java9_v2Parser::TryStatement2Context *ctx);

    antlrcpp::Any visitTryStatement3(Java9_v2Parser::TryStatement3Context *ctx);

    antlrcpp::Any visitTryStatement1(Java9_v2Parser::TryStatement1Context *ctx);

    antlrcpp::Any visitCatches(Java9_v2Parser::CatchesContext *ctx);

    antlrcpp::Any visitCatchClause(Java9_v2Parser::CatchClauseContext *ctx);

    antlrcpp::Any visitCatchFormalParameter(Java9_v2Parser::CatchFormalParameterContext *ctx);

    antlrcpp::Any visitCatchType(Java9_v2Parser::CatchTypeContext *ctx);

    antlrcpp::Any visitFinally_(Java9_v2Parser::Finally_Context *ctx);

    antlrcpp::Any visitTryWithResourcesStatement(Java9_v2Parser::TryWithResourcesStatementContext *ctx);

    antlrcpp::Any visitResourceSpecification(Java9_v2Parser::ResourceSpecificationContext *ctx);

    antlrcpp::Any visitResourceList(Java9_v2Parser::ResourceListContext *ctx);

    antlrcpp::Any visitResource2(Java9_v2Parser::Resource2Context *ctx);

    antlrcpp::Any visitResource1(Java9_v2Parser::Resource1Context *ctx);

    antlrcpp::Any visitVariableAccess1(Java9_v2Parser::VariableAccess1Context *ctx);

    antlrcpp::Any visitVariableAccess2(Java9_v2Parser::VariableAccess2Context *ctx);

    antlrcpp::Any visitPrimary(Java9_v2Parser::PrimaryContext *ctx);

    antlrcpp::Any visitPrimaryNoNewArray1(Java9_v2Parser::PrimaryNoNewArray1Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray2(Java9_v2Parser::PrimaryNoNewArray2Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray3(Java9_v2Parser::PrimaryNoNewArray3Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray8(Java9_v2Parser::PrimaryNoNewArray8Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray9(Java9_v2Parser::PrimaryNoNewArray9Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray4(Java9_v2Parser::PrimaryNoNewArray4Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray5(Java9_v2Parser::PrimaryNoNewArray5Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray6(Java9_v2Parser::PrimaryNoNewArray6Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray10(Java9_v2Parser::PrimaryNoNewArray10Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray7(Java9_v2Parser::PrimaryNoNewArray7Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray_lf_arrayAccess(Java9_v2Parser::PrimaryNoNewArray_lf_arrayAccessContext *ctx);

    antlrcpp::Any visitPrimaryNoNewArray_lfno_arrayAccess6(Java9_v2Parser::PrimaryNoNewArray_lfno_arrayAccess6Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray_lfno_arrayAccess10(Java9_v2Parser::PrimaryNoNewArray_lfno_arrayAccess10Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray_lfno_arrayAccess7(Java9_v2Parser::PrimaryNoNewArray_lfno_arrayAccess7Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray_lfno_arrayAccess4(Java9_v2Parser::PrimaryNoNewArray_lfno_arrayAccess4Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray_lfno_arrayAccess5(Java9_v2Parser::PrimaryNoNewArray_lfno_arrayAccess5Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray_lfno_arrayAccess8(Java9_v2Parser::PrimaryNoNewArray_lfno_arrayAccess8Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray_lfno_arrayAccess9(Java9_v2Parser::PrimaryNoNewArray_lfno_arrayAccess9Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray_lfno_arrayAccess2(Java9_v2Parser::PrimaryNoNewArray_lfno_arrayAccess2Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray_lfno_arrayAccess3(Java9_v2Parser::PrimaryNoNewArray_lfno_arrayAccess3Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray_lfno_arrayAccess1(Java9_v2Parser::PrimaryNoNewArray_lfno_arrayAccess1Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray_lf_primary2(Java9_v2Parser::PrimaryNoNewArray_lf_primary2Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray_lf_primary3(Java9_v2Parser::PrimaryNoNewArray_lf_primary3Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray_lf_primary1(Java9_v2Parser::PrimaryNoNewArray_lf_primary1Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray_lf_primary4(Java9_v2Parser::PrimaryNoNewArray_lf_primary4Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray_lf_primary5(Java9_v2Parser::PrimaryNoNewArray_lf_primary5Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray_lf_primary_lf_arrayAccess_lf_primary(Java9_v2Parser::PrimaryNoNewArray_lf_primary_lf_arrayAccess_lf_primaryContext *ctx);

    antlrcpp::Any visitPrimaryNoNewArray_lf_primary_lfno_arrayAccess_lf_primary1(Java9_v2Parser::PrimaryNoNewArray_lf_primary_lfno_arrayAccess_lf_primary1Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray_lf_primary_lfno_arrayAccess_lf_primary3(Java9_v2Parser::PrimaryNoNewArray_lf_primary_lfno_arrayAccess_lf_primary3Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray_lf_primary_lfno_arrayAccess_lf_primary2(Java9_v2Parser::PrimaryNoNewArray_lf_primary_lfno_arrayAccess_lf_primary2Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray_lf_primary_lfno_arrayAccess_lf_primary4(Java9_v2Parser::PrimaryNoNewArray_lf_primary_lfno_arrayAccess_lf_primary4Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray_lfno_primary9(Java9_v2Parser::PrimaryNoNewArray_lfno_primary9Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray_lfno_primary5(Java9_v2Parser::PrimaryNoNewArray_lfno_primary5Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray_lfno_primary6(Java9_v2Parser::PrimaryNoNewArray_lfno_primary6Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray_lfno_primary7(Java9_v2Parser::PrimaryNoNewArray_lfno_primary7Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray_lfno_primary8(Java9_v2Parser::PrimaryNoNewArray_lfno_primary8Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray_lfno_primary1(Java9_v2Parser::PrimaryNoNewArray_lfno_primary1Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray_lfno_primary2(Java9_v2Parser::PrimaryNoNewArray_lfno_primary2Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray_lfno_primary12(Java9_v2Parser::PrimaryNoNewArray_lfno_primary12Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray_lfno_primary3(Java9_v2Parser::PrimaryNoNewArray_lfno_primary3Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray_lfno_primary11(Java9_v2Parser::PrimaryNoNewArray_lfno_primary11Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray_lfno_primary4(Java9_v2Parser::PrimaryNoNewArray_lfno_primary4Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray_lfno_primary10(Java9_v2Parser::PrimaryNoNewArray_lfno_primary10Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray_lfno_primary_lf_arrayAccess_lfno_primary(Java9_v2Parser::PrimaryNoNewArray_lfno_primary_lf_arrayAccess_lfno_primaryContext *ctx);

    antlrcpp::Any visitPrimaryNoNewArray_lfno_primary_lfno_arrayAccess_lfno_primary3(Java9_v2Parser::PrimaryNoNewArray_lfno_primary_lfno_arrayAccess_lfno_primary3Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray_lfno_primary_lfno_arrayAccess_lfno_primary11(Java9_v2Parser::PrimaryNoNewArray_lfno_primary_lfno_arrayAccess_lfno_primary11Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray_lfno_primary_lfno_arrayAccess_lfno_primary2(Java9_v2Parser::PrimaryNoNewArray_lfno_primary_lfno_arrayAccess_lfno_primary2Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray_lfno_primary_lfno_arrayAccess_lfno_primary5(Java9_v2Parser::PrimaryNoNewArray_lfno_primary_lfno_arrayAccess_lfno_primary5Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray_lfno_primary_lfno_arrayAccess_lfno_primary4(Java9_v2Parser::PrimaryNoNewArray_lfno_primary_lfno_arrayAccess_lfno_primary4Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray_lfno_primary_lfno_arrayAccess_lfno_primary10(Java9_v2Parser::PrimaryNoNewArray_lfno_primary_lfno_arrayAccess_lfno_primary10Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray_lfno_primary_lfno_arrayAccess_lfno_primary1(Java9_v2Parser::PrimaryNoNewArray_lfno_primary_lfno_arrayAccess_lfno_primary1Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray_lfno_primary_lfno_arrayAccess_lfno_primary7(Java9_v2Parser::PrimaryNoNewArray_lfno_primary_lfno_arrayAccess_lfno_primary7Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray_lfno_primary_lfno_arrayAccess_lfno_primary6(Java9_v2Parser::PrimaryNoNewArray_lfno_primary_lfno_arrayAccess_lfno_primary6Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray_lfno_primary_lfno_arrayAccess_lfno_primary9(Java9_v2Parser::PrimaryNoNewArray_lfno_primary_lfno_arrayAccess_lfno_primary9Context *ctx);

    antlrcpp::Any visitPrimaryNoNewArray_lfno_primary_lfno_arrayAccess_lfno_primary8(Java9_v2Parser::PrimaryNoNewArray_lfno_primary_lfno_arrayAccess_lfno_primary8Context *ctx);

    antlrcpp::Any visitClassLiteral2(Java9_v2Parser::ClassLiteral2Context *ctx);

    antlrcpp::Any visitClassLiteral1(Java9_v2Parser::ClassLiteral1Context *ctx);

    antlrcpp::Any visitClassInstanceCreationExpression1(Java9_v2Parser::ClassInstanceCreationExpression1Context *ctx);

    antlrcpp::Any visitClassInstanceCreationExpression3(Java9_v2Parser::ClassInstanceCreationExpression3Context *ctx);

    antlrcpp::Any visitClassInstanceCreationExpression2(Java9_v2Parser::ClassInstanceCreationExpression2Context *ctx);

    antlrcpp::Any visitClassInstanceCreationExpression_lf_primary(Java9_v2Parser::ClassInstanceCreationExpression_lf_primaryContext *ctx);

    antlrcpp::Any visitClassInstanceCreationExpression_lfno_primary1(Java9_v2Parser::ClassInstanceCreationExpression_lfno_primary1Context *ctx);

    antlrcpp::Any visitClassInstanceCreationExpression_lfno_primary2(Java9_v2Parser::ClassInstanceCreationExpression_lfno_primary2Context *ctx);

    antlrcpp::Any visitTypeArgumentsOrDiamond1(Java9_v2Parser::TypeArgumentsOrDiamond1Context *ctx);

    antlrcpp::Any visitTypeArgumentsOrDiamond2(Java9_v2Parser::TypeArgumentsOrDiamond2Context *ctx);

    antlrcpp::Any visitFieldAccess1(Java9_v2Parser::FieldAccess1Context *ctx);

    antlrcpp::Any visitFieldAccess2(Java9_v2Parser::FieldAccess2Context *ctx);

    antlrcpp::Any visitFieldAccess3(Java9_v2Parser::FieldAccess3Context *ctx);

    antlrcpp::Any visitFieldAccess_lf_primary(Java9_v2Parser::FieldAccess_lf_primaryContext *ctx);

    antlrcpp::Any visitFieldAccess_lfno_primary2(Java9_v2Parser::FieldAccess_lfno_primary2Context *ctx);

    antlrcpp::Any visitFieldAccess_lfno_primary1(Java9_v2Parser::FieldAccess_lfno_primary1Context *ctx);

    antlrcpp::Any visitArrayAccess(Java9_v2Parser::ArrayAccessContext *ctx);

    antlrcpp::Any visitArrayAccess_lf_primary(Java9_v2Parser::ArrayAccess_lf_primaryContext *ctx);

    antlrcpp::Any visitArrayAccess_lfno_primary(Java9_v2Parser::ArrayAccess_lfno_primaryContext *ctx);

    antlrcpp::Any visitMethodInvocation1(Java9_v2Parser::MethodInvocation1Context *ctx);

    antlrcpp::Any visitMethodInvocation2(Java9_v2Parser::MethodInvocation2Context *ctx);

    antlrcpp::Any visitMethodInvocation3(Java9_v2Parser::MethodInvocation3Context *ctx);

    antlrcpp::Any visitMethodInvocation4(Java9_v2Parser::MethodInvocation4Context *ctx);

    antlrcpp::Any visitMethodInvocation5(Java9_v2Parser::MethodInvocation5Context *ctx);

    antlrcpp::Any visitMethodInvocation6(Java9_v2Parser::MethodInvocation6Context *ctx);

    antlrcpp::Any visitMethodInvocation_lf_primary(Java9_v2Parser::MethodInvocation_lf_primaryContext *ctx);

    antlrcpp::Any visitMethodInvocation_lfno_primary3(Java9_v2Parser::MethodInvocation_lfno_primary3Context *ctx);

    antlrcpp::Any visitMethodInvocation_lfno_primary2(Java9_v2Parser::MethodInvocation_lfno_primary2Context *ctx);

    antlrcpp::Any visitMethodInvocation_lfno_primary1(Java9_v2Parser::MethodInvocation_lfno_primary1Context *ctx);

    antlrcpp::Any visitMethodInvocation_lfno_primary5(Java9_v2Parser::MethodInvocation_lfno_primary5Context *ctx);

    antlrcpp::Any visitMethodInvocation_lfno_primary4(Java9_v2Parser::MethodInvocation_lfno_primary4Context *ctx);

    antlrcpp::Any visitArgumentList(Java9_v2Parser::ArgumentListContext *ctx);

    antlrcpp::Any visitMethodReference1(Java9_v2Parser::MethodReference1Context *ctx);

    antlrcpp::Any visitMethodReference3(Java9_v2Parser::MethodReference3Context *ctx);

    antlrcpp::Any visitMethodReference2(Java9_v2Parser::MethodReference2Context *ctx);

    antlrcpp::Any visitMethodReference5(Java9_v2Parser::MethodReference5Context *ctx);

    antlrcpp::Any visitMethodReference4(Java9_v2Parser::MethodReference4Context *ctx);

    antlrcpp::Any visitMethodReference7(Java9_v2Parser::MethodReference7Context *ctx);

    antlrcpp::Any visitMethodReference6(Java9_v2Parser::MethodReference6Context *ctx);

    antlrcpp::Any visitMethodReference_lf_primary(Java9_v2Parser::MethodReference_lf_primaryContext *ctx);

    antlrcpp::Any visitMethodReference_lfno_primary6(Java9_v2Parser::MethodReference_lfno_primary6Context *ctx);

    antlrcpp::Any visitMethodReference_lfno_primary5(Java9_v2Parser::MethodReference_lfno_primary5Context *ctx);

    antlrcpp::Any visitMethodReference_lfno_primary4(Java9_v2Parser::MethodReference_lfno_primary4Context *ctx);

    antlrcpp::Any visitMethodReference_lfno_primary3(Java9_v2Parser::MethodReference_lfno_primary3Context *ctx);

    antlrcpp::Any visitMethodReference_lfno_primary2(Java9_v2Parser::MethodReference_lfno_primary2Context *ctx);

    antlrcpp::Any visitMethodReference_lfno_primary1(Java9_v2Parser::MethodReference_lfno_primary1Context *ctx);

    antlrcpp::Any visitArrayCreationExpression4(Java9_v2Parser::ArrayCreationExpression4Context *ctx);

    antlrcpp::Any visitArrayCreationExpression2(Java9_v2Parser::ArrayCreationExpression2Context *ctx);

    antlrcpp::Any visitArrayCreationExpression3(Java9_v2Parser::ArrayCreationExpression3Context *ctx);

    antlrcpp::Any visitArrayCreationExpression1(Java9_v2Parser::ArrayCreationExpression1Context *ctx);

    antlrcpp::Any visitDimExprs(Java9_v2Parser::DimExprsContext *ctx);

    antlrcpp::Any visitDimExpr(Java9_v2Parser::DimExprContext *ctx);

    antlrcpp::Any visitConstantExpression(Java9_v2Parser::ConstantExpressionContext *ctx);

    antlrcpp::Any visitExpression2(Java9_v2Parser::Expression2Context *ctx);

    antlrcpp::Any visitExpression1(Java9_v2Parser::Expression1Context *ctx);

    antlrcpp::Any visitLambdaExpression(Java9_v2Parser::LambdaExpressionContext *ctx);

    antlrcpp::Any visitLambdaParameters3(Java9_v2Parser::LambdaParameters3Context *ctx);

    antlrcpp::Any visitLambdaParameters1(Java9_v2Parser::LambdaParameters1Context *ctx);

    antlrcpp::Any visitLambdaParameters2(Java9_v2Parser::LambdaParameters2Context *ctx);

    antlrcpp::Any visitInferredFormalParameterList(Java9_v2Parser::InferredFormalParameterListContext *ctx);

    antlrcpp::Any visitLambdaBody1(Java9_v2Parser::LambdaBody1Context *ctx);

    antlrcpp::Any visitLambdaBody2(Java9_v2Parser::LambdaBody2Context *ctx);

    antlrcpp::Any visitAssignmentExpression1(Java9_v2Parser::AssignmentExpression1Context *ctx);

    antlrcpp::Any visitAssignmentExpression2(Java9_v2Parser::AssignmentExpression2Context *ctx);

    antlrcpp::Any visitAssignment(Java9_v2Parser::AssignmentContext *ctx);

    antlrcpp::Any visitLeftHandSide5(Java9_v2Parser::LeftHandSide5Context *ctx);

    antlrcpp::Any visitLeftHandSide4(Java9_v2Parser::LeftHandSide4Context *ctx);

    antlrcpp::Any visitLeftHandSide3(Java9_v2Parser::LeftHandSide3Context *ctx);

    antlrcpp::Any visitAssignmentOperator(Java9_v2Parser::AssignmentOperatorContext *ctx);

    antlrcpp::Any visitConditionalExpression1(Java9_v2Parser::ConditionalExpression1Context *ctx);

    antlrcpp::Any visitConditionalExpression2(Java9_v2Parser::ConditionalExpression2Context *ctx);

    antlrcpp::Any visitConditionalOrExpression1(Java9_v2Parser::ConditionalOrExpression1Context *ctx);

    antlrcpp::Any visitConditionalOrExpression2(Java9_v2Parser::ConditionalOrExpression2Context *ctx);

    antlrcpp::Any visitConditionalAndExpression2(Java9_v2Parser::ConditionalAndExpression2Context *ctx);

    antlrcpp::Any visitConditionalAndExpression1(Java9_v2Parser::ConditionalAndExpression1Context *ctx);

    antlrcpp::Any visitInclusiveOrExpression2(Java9_v2Parser::InclusiveOrExpression2Context *ctx);

    antlrcpp::Any visitInclusiveOrExpression1(Java9_v2Parser::InclusiveOrExpression1Context *ctx);

    antlrcpp::Any visitExclusiveOrExpression1(Java9_v2Parser::ExclusiveOrExpression1Context *ctx);

    antlrcpp::Any visitExclusiveOrExpression2(Java9_v2Parser::ExclusiveOrExpression2Context *ctx);

    antlrcpp::Any visitAndExpression2(Java9_v2Parser::AndExpression2Context *ctx);

    antlrcpp::Any visitAndExpression1(Java9_v2Parser::AndExpression1Context *ctx);

    antlrcpp::Any visitEqualityExpression3(Java9_v2Parser::EqualityExpression3Context *ctx);

    antlrcpp::Any visitEqualityExpression2(Java9_v2Parser::EqualityExpression2Context *ctx);

    antlrcpp::Any visitEqualityExpression1(Java9_v2Parser::EqualityExpression1Context *ctx);

    antlrcpp::Any visitRelationalExpression1(Java9_v2Parser::RelationalExpression1Context *ctx);

    antlrcpp::Any visitRelationalExpression2(Java9_v2Parser::RelationalExpression2Context *ctx);

    antlrcpp::Any visitRelationalExpression5(Java9_v2Parser::RelationalExpression5Context *ctx);

    antlrcpp::Any visitRelationalExpression6(Java9_v2Parser::RelationalExpression6Context *ctx);

    antlrcpp::Any visitRelationalExpression3(Java9_v2Parser::RelationalExpression3Context *ctx);

    antlrcpp::Any visitRelationalExpression4(Java9_v2Parser::RelationalExpression4Context *ctx);

    antlrcpp::Any visitShiftExpression1(Java9_v2Parser::ShiftExpression1Context *ctx);

    antlrcpp::Any visitShiftExpression3(Java9_v2Parser::ShiftExpression3Context *ctx);

    antlrcpp::Any visitShiftExpression2(Java9_v2Parser::ShiftExpression2Context *ctx);

    antlrcpp::Any visitShiftExpression4(Java9_v2Parser::ShiftExpression4Context *ctx);

    antlrcpp::Any visitAdditiveExpression1(Java9_v2Parser::AdditiveExpression1Context *ctx);

    antlrcpp::Any visitAdditiveExpression3(Java9_v2Parser::AdditiveExpression3Context *ctx);

    antlrcpp::Any visitAdditiveExpressio2(Java9_v2Parser::AdditiveExpressio2Context *ctx);

    antlrcpp::Any visitMultiplicativeExpression1(Java9_v2Parser::MultiplicativeExpression1Context *ctx);

    antlrcpp::Any visitMultiplicativeExpression4(Java9_v2Parser::MultiplicativeExpression4Context *ctx);

    antlrcpp::Any visitMultiplicativeExpression3(Java9_v2Parser::MultiplicativeExpression3Context *ctx);

    antlrcpp::Any visitMultiplicativeExpression2(Java9_v2Parser::MultiplicativeExpression2Context *ctx);

    antlrcpp::Any visitUnaryExpression2(Java9_v2Parser::UnaryExpression2Context *ctx);

    antlrcpp::Any visitUnaryExpression1(Java9_v2Parser::UnaryExpression1Context *ctx);

    antlrcpp::Any visitUnaryExpression5(Java9_v2Parser::UnaryExpression5Context *ctx);

    antlrcpp::Any visitUnaryExpression4(Java9_v2Parser::UnaryExpression4Context *ctx);

    antlrcpp::Any visitUnaryExpression3(Java9_v2Parser::UnaryExpression3Context *ctx);

    antlrcpp::Any visitPreIncrementExpression(Java9_v2Parser::PreIncrementExpressionContext *ctx);

    antlrcpp::Any visitPreDecrementExpression(Java9_v2Parser::PreDecrementExpressionContext *ctx);

    antlrcpp::Any visitUnaryExpressionNotPlusMinus4(Java9_v2Parser::UnaryExpressionNotPlusMinus4Context *ctx);

    antlrcpp::Any visitUnaryExpressionNotPlusMinus3(Java9_v2Parser::UnaryExpressionNotPlusMinus3Context *ctx);

    antlrcpp::Any visitUnaryExpressionNotPlusMinus2(Java9_v2Parser::UnaryExpressionNotPlusMinus2Context *ctx);

    antlrcpp::Any visitUnaryExpressionNotPlusMinus1(Java9_v2Parser::UnaryExpressionNotPlusMinus1Context *ctx);

    antlrcpp::Any visitPostfixExpression(Java9_v2Parser::PostfixExpressionContext *ctx);

    antlrcpp::Any visitPostIncrementExpression(Java9_v2Parser::PostIncrementExpressionContext *ctx);

    antlrcpp::Any visitPostIncrementExpression_lf_postfixExpression(Java9_v2Parser::PostIncrementExpression_lf_postfixExpressionContext *ctx);

    antlrcpp::Any visitPostDecrementExpression(Java9_v2Parser::PostDecrementExpressionContext *ctx);

    antlrcpp::Any visitPostDecrementExpression_lf_postfixExpression(Java9_v2Parser::PostDecrementExpression_lf_postfixExpressionContext *ctx);

    antlrcpp::Any visitCastExpression3(Java9_v2Parser::CastExpression3Context *ctx);

    antlrcpp::Any visitCastExpression1(Java9_v2Parser::CastExpression1Context *ctx);

    antlrcpp::Any visitCastExpression2(Java9_v2Parser::CastExpression2Context *ctx);

    antlrcpp::Any visitIdentifier(Java9_v2Parser::IdentifierContext *ctx);

};