FROM ubuntu:jammy-20250415.1

RUN apk upgrade --update-cache --available && \
    apk add openssl && \
    rm -rf /var/cache/apk/*

FROM python:3.12-slim

USER root


WORKDIR /app

ENV PATH=/app/scitools/bin/linux64:$PATH
ENV PYTHONPATH=/app/scitools/bin/linux64/Python:$PYTHONPATH
ENV LD_LIBRARY_PATH=/app/scitools/bin/linux64:$LD_LIBRARY_PATH
ENV CFLAGS="-I/usr/local/ssl/include"
ENV LDFLAGS="-L/usr/local/ssl/lib"

COPY dependencies/* /app/dependencies/

RUN pip3 install /app/dependencies/*