FROM alpine:edge

RUN apk upgrade --update-cache --available && \
    apk add openssl && \
    rm -rf /var/cache/apk/*

FROM python:3.12-slim

WORKDIR /app

# Configure the system to use the compiled OpenSSL
ENV PATH=/usr/local/ssl/bin:$PATH
ENV LD_LIBRARY_PATH=/usr/local/ssl/lib:$LD_LIBRARY_PATH
ENV CFLAGS="-I/usr/local/ssl/include"
ENV LDFLAGS="-L/usr/local/ssl/lib"

COPY dependencies/* /app/dependencies/

RUN pip3 install --no-cache-dir /app/dependencies/*