/* Before refactoring (Original version) */
class A
{
    public int f; /* printF , printF, */
    public int g; /* printF, printG */
     /* printH */

    // Method 1
    void printF(int i)
    {
        this.f = i * this.f;
    }

    // Method 2
    void printF(float i){
        this.f = (int) (i * this.f);
        this.g = (int) (i * this.g);
    }

    // Method 3
    void printG(){
        print(this.g);
    }

    // Method 4
    
}

// New class(APlus) generated by CodART
class APlus
{
	public string h;

	void printH(){
        print(this.h);
    }
}


class B{

    public string instance;

    public B(A a_instance){
        this.instance = a_instance.h;
    }
}