/*
 * This file was auto-generated by speedy-antlr-tool v1.3.1
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#pragma once

#include "JavaLabeledParserBaseVisitor.h"
#include "speedy_antlr.h"

class SA_JavaLabeledTranslator : public JavaLabeledParserBaseVisitor {
    speedy_antlr::Translator *translator;

    // Cached context classes
    PyObject *CompilationUnitContext_cls = NULL;
    PyObject *PackageDeclarationContext_cls = NULL;
    PyObject *ImportDeclarationContext_cls = NULL;
    PyObject *TypeDeclarationContext_cls = NULL;
    PyObject *ModifierContext_cls = NULL;
    PyObject *ClassOrInterfaceModifierContext_cls = NULL;
    PyObject *VariableModifierContext_cls = NULL;
    PyObject *ClassDeclarationContext_cls = NULL;
    PyObject *TypeParametersContext_cls = NULL;
    PyObject *TypeParameterContext_cls = NULL;
    PyObject *TypeBoundContext_cls = NULL;
    PyObject *EnumDeclarationContext_cls = NULL;
    PyObject *EnumConstantsContext_cls = NULL;
    PyObject *EnumConstantContext_cls = NULL;
    PyObject *EnumBodyDeclarationsContext_cls = NULL;
    PyObject *InterfaceDeclarationContext_cls = NULL;
    PyObject *ClassBodyContext_cls = NULL;
    PyObject *InterfaceBodyContext_cls = NULL;
    PyObject *ClassBodyDeclaration1Context_cls = NULL;
    PyObject *ClassBodyDeclaration0Context_cls = NULL;
    PyObject *ClassBodyDeclaration2Context_cls = NULL;
    PyObject *MemberDeclaration8Context_cls = NULL;
    PyObject *MemberDeclaration0Context_cls = NULL;
    PyObject *MemberDeclaration1Context_cls = NULL;
    PyObject *MemberDeclaration2Context_cls = NULL;
    PyObject *MemberDeclaration3Context_cls = NULL;
    PyObject *MemberDeclaration4Context_cls = NULL;
    PyObject *MemberDeclaration5Context_cls = NULL;
    PyObject *MemberDeclaration6Context_cls = NULL;
    PyObject *MemberDeclaration7Context_cls = NULL;
    PyObject *MethodDeclarationContext_cls = NULL;
    PyObject *MethodBodyContext_cls = NULL;
    PyObject *TypeTypeOrVoidContext_cls = NULL;
    PyObject *GenericMethodDeclarationContext_cls = NULL;
    PyObject *GenericConstructorDeclarationContext_cls = NULL;
    PyObject *ConstructorDeclarationContext_cls = NULL;
    PyObject *FieldDeclarationContext_cls = NULL;
    PyObject *InterfaceBodyDeclarationContext_cls = NULL;
    PyObject *InterfaceMemberDeclaration6Context_cls = NULL;
    PyObject *InterfaceMemberDeclaration5Context_cls = NULL;
    PyObject *InterfaceMemberDeclaration4Context_cls = NULL;
    PyObject *InterfaceMemberDeclaration3Context_cls = NULL;
    PyObject *InterfaceMemberDeclaration2Context_cls = NULL;
    PyObject *InterfaceMemberDeclaration1Context_cls = NULL;
    PyObject *InterfaceMemberDeclaration0Context_cls = NULL;
    PyObject *ConstDeclarationContext_cls = NULL;
    PyObject *ConstantDeclaratorContext_cls = NULL;
    PyObject *InterfaceMethodDeclarationContext_cls = NULL;
    PyObject *InterfaceMethodModifierContext_cls = NULL;
    PyObject *GenericInterfaceMethodDeclarationContext_cls = NULL;
    PyObject *VariableDeclaratorsContext_cls = NULL;
    PyObject *VariableDeclaratorContext_cls = NULL;
    PyObject *VariableDeclaratorIdContext_cls = NULL;
    PyObject *VariableInitializer1Context_cls = NULL;
    PyObject *VariableInitializer0Context_cls = NULL;
    PyObject *ArrayInitializerContext_cls = NULL;
    PyObject *ClassOrInterfaceTypeContext_cls = NULL;
    PyObject *TypeArgument0Context_cls = NULL;
    PyObject *QualifiedNameListContext_cls = NULL;
    PyObject *FormalParametersContext_cls = NULL;
    PyObject *FormalParameterList1Context_cls = NULL;
    PyObject *FormalParameterList0Context_cls = NULL;
    PyObject *FormalParameterContext_cls = NULL;
    PyObject *LastFormalParameterContext_cls = NULL;
    PyObject *QualifiedNameContext_cls = NULL;
    PyObject *Literal2Context_cls = NULL;
    PyObject *Literal1Context_cls = NULL;
    PyObject *Literal0Context_cls = NULL;
    PyObject *Literal5Context_cls = NULL;
    PyObject *Literal4Context_cls = NULL;
    PyObject *Literal3Context_cls = NULL;
    PyObject *IntegerLiteralContext_cls = NULL;
    PyObject *FloatLiteralContext_cls = NULL;
    PyObject *AltAnnotationQualifiedNameContext_cls = NULL;
    PyObject *AnnotationContext_cls = NULL;
    PyObject *ElementValuePairsContext_cls = NULL;
    PyObject *ElementValuePairContext_cls = NULL;
    PyObject *ElementValue0Context_cls = NULL;
    PyObject *ElementValue2Context_cls = NULL;
    PyObject *ElementValue1Context_cls = NULL;
    PyObject *ElementValueArrayInitializerContext_cls = NULL;
    PyObject *AnnotationTypeDeclarationContext_cls = NULL;
    PyObject *AnnotationTypeBodyContext_cls = NULL;
    PyObject *AnnotationTypeElementDeclarationContext_cls = NULL;
    PyObject *AnnotationTypeElementRest0Context_cls = NULL;
    PyObject *AnnotationTypeElementRest1Context_cls = NULL;
    PyObject *AnnotationTypeElementRest2Context_cls = NULL;
    PyObject *AnnotationTypeElementRest3Context_cls = NULL;
    PyObject *AnnotationTypeElementRest4Context_cls = NULL;
    PyObject *AnnotationMethodOrConstantRest0Context_cls = NULL;
    PyObject *AnnotationMethodOrConstantRest1Context_cls = NULL;
    PyObject *AnnotationMethodRestContext_cls = NULL;
    PyObject *AnnotationConstantRestContext_cls = NULL;
    PyObject *DefaultValueContext_cls = NULL;
    PyObject *BlockContext_cls = NULL;
    PyObject *BlockStatement1Context_cls = NULL;
    PyObject *BlockStatement0Context_cls = NULL;
    PyObject *BlockStatement2Context_cls = NULL;
    PyObject *LocalVariableDeclarationContext_cls = NULL;
    PyObject *LocalTypeDeclarationContext_cls = NULL;
    PyObject *Statement14Context_cls = NULL;
    PyObject *Statement15Context_cls = NULL;
    PyObject *Statement12Context_cls = NULL;
    PyObject *Statement13Context_cls = NULL;
    PyObject *Statement9Context_cls = NULL;
    PyObject *Statement7Context_cls = NULL;
    PyObject *Statement16Context_cls = NULL;
    PyObject *Statement8Context_cls = NULL;
    PyObject *Statement5Context_cls = NULL;
    PyObject *Statement6Context_cls = NULL;
    PyObject *Statement3Context_cls = NULL;
    PyObject *Statement4Context_cls = NULL;
    PyObject *Statement1Context_cls = NULL;
    PyObject *Statement2Context_cls = NULL;
    PyObject *Statement0Context_cls = NULL;
    PyObject *Statement10Context_cls = NULL;
    PyObject *Statement11Context_cls = NULL;
    PyObject *CatchClauseContext_cls = NULL;
    PyObject *CatchTypeContext_cls = NULL;
    PyObject *FinallyBlockContext_cls = NULL;
    PyObject *ResourceSpecificationContext_cls = NULL;
    PyObject *ResourcesContext_cls = NULL;
    PyObject *ResourceContext_cls = NULL;
    PyObject *SwitchBlockStatementGroupContext_cls = NULL;
    PyObject *SwitchLabelContext_cls = NULL;
    PyObject *ForControl0Context_cls = NULL;
    PyObject *ForControl1Context_cls = NULL;
    PyObject *ForInit1Context_cls = NULL;
    PyObject *ForInit0Context_cls = NULL;
    PyObject *EnhancedForControlContext_cls = NULL;
    PyObject *ParExpressionContext_cls = NULL;
    PyObject *ExpressionListContext_cls = NULL;
    PyObject *MethodCall0Context_cls = NULL;
    PyObject *MethodCall1Context_cls = NULL;
    PyObject *MethodCall2Context_cls = NULL;
    PyObject *Expression8Context_cls = NULL;
    PyObject *Expression10Context_cls = NULL;
    PyObject *Expression9Context_cls = NULL;
    PyObject *Expression12Context_cls = NULL;
    PyObject *Expression11Context_cls = NULL;
    PyObject *Expression14Context_cls = NULL;
    PyObject *Expression13Context_cls = NULL;
    PyObject *Expression16Context_cls = NULL;
    PyObject *Expression15Context_cls = NULL;
    PyObject *Expression18Context_cls = NULL;
    PyObject *Expression17Context_cls = NULL;
    PyObject *Expression19Context_cls = NULL;
    PyObject *Expression6Context_cls = NULL;
    PyObject *Expression7Context_cls = NULL;
    PyObject *Expression4Context_cls = NULL;
    PyObject *Expression5Context_cls = NULL;
    PyObject *Expression2Context_cls = NULL;
    PyObject *Expression3Context_cls = NULL;
    PyObject *Expression0Context_cls = NULL;
    PyObject *Expression1Context_cls = NULL;
    PyObject *Expression21Context_cls = NULL;
    PyObject *Expression20Context_cls = NULL;
    PyObject *Expression23Context_cls = NULL;
    PyObject *Expression22Context_cls = NULL;
    PyObject *Expression25Context_cls = NULL;
    PyObject *Expression24Context_cls = NULL;
    PyObject *LambdaExpressionContext_cls = NULL;
    PyObject *LambdaParameters0Context_cls = NULL;
    PyObject *LambdaParameters1Context_cls = NULL;
    PyObject *LambdaParameters2Context_cls = NULL;
    PyObject *LambdaBody0Context_cls = NULL;
    PyObject *LambdaBody1Context_cls = NULL;
    PyObject *Primary6Context_cls = NULL;
    PyObject *Primary2Context_cls = NULL;
    PyObject *Primary3Context_cls = NULL;
    PyObject *Primary4Context_cls = NULL;
    PyObject *Primary5Context_cls = NULL;
    PyObject *Primary0Context_cls = NULL;
    PyObject *Primary1Context_cls = NULL;
    PyObject *ClassTypeContext_cls = NULL;
    PyObject *Creator1Context_cls = NULL;
    PyObject *Creator0Context_cls = NULL;
    PyObject *CreatedName0Context_cls = NULL;
    PyObject *CreatedName1Context_cls = NULL;
    PyObject *InnerCreatorContext_cls = NULL;
    PyObject *ArrayCreatorRestContext_cls = NULL;
    PyObject *ClassCreatorRestContext_cls = NULL;
    PyObject *ExplicitGenericInvocationContext_cls = NULL;
    PyObject *TypeArgumentsOrDiamondContext_cls = NULL;
    PyObject *NonWildcardTypeArgumentsOrDiamondContext_cls = NULL;
    PyObject *NonWildcardTypeArgumentsContext_cls = NULL;
    PyObject *TypeListContext_cls = NULL;
    PyObject *TypeTypeContext_cls = NULL;
    PyObject *PrimitiveTypeContext_cls = NULL;
    PyObject *TypeArgumentsContext_cls = NULL;
    PyObject *SuperSuffix1Context_cls = NULL;
    PyObject *SuperSuffix0Context_cls = NULL;
    PyObject *ExplicitGenericInvocationSuffix0Context_cls = NULL;
    PyObject *ExplicitGenericInvocationSuffix1Context_cls = NULL;
    PyObject *ArgumentsContext_cls = NULL;

    public:
    SA_JavaLabeledTranslator(speedy_antlr::Translator *translator);
    ~SA_JavaLabeledTranslator();
    antlrcpp::Any visitCompilationUnit(JavaLabeledParser::CompilationUnitContext *ctx);

    antlrcpp::Any visitPackageDeclaration(JavaLabeledParser::PackageDeclarationContext *ctx);

    antlrcpp::Any visitImportDeclaration(JavaLabeledParser::ImportDeclarationContext *ctx);

    antlrcpp::Any visitTypeDeclaration(JavaLabeledParser::TypeDeclarationContext *ctx);

    antlrcpp::Any visitModifier(JavaLabeledParser::ModifierContext *ctx);

    antlrcpp::Any visitClassOrInterfaceModifier(JavaLabeledParser::ClassOrInterfaceModifierContext *ctx);

    antlrcpp::Any visitVariableModifier(JavaLabeledParser::VariableModifierContext *ctx);

    antlrcpp::Any visitClassDeclaration(JavaLabeledParser::ClassDeclarationContext *ctx);

    antlrcpp::Any visitTypeParameters(JavaLabeledParser::TypeParametersContext *ctx);

    antlrcpp::Any visitTypeParameter(JavaLabeledParser::TypeParameterContext *ctx);

    antlrcpp::Any visitTypeBound(JavaLabeledParser::TypeBoundContext *ctx);

    antlrcpp::Any visitEnumDeclaration(JavaLabeledParser::EnumDeclarationContext *ctx);

    antlrcpp::Any visitEnumConstants(JavaLabeledParser::EnumConstantsContext *ctx);

    antlrcpp::Any visitEnumConstant(JavaLabeledParser::EnumConstantContext *ctx);

    antlrcpp::Any visitEnumBodyDeclarations(JavaLabeledParser::EnumBodyDeclarationsContext *ctx);

    antlrcpp::Any visitInterfaceDeclaration(JavaLabeledParser::InterfaceDeclarationContext *ctx);

    antlrcpp::Any visitClassBody(JavaLabeledParser::ClassBodyContext *ctx);

    antlrcpp::Any visitInterfaceBody(JavaLabeledParser::InterfaceBodyContext *ctx);

    antlrcpp::Any visitClassBodyDeclaration1(JavaLabeledParser::ClassBodyDeclaration1Context *ctx);

    antlrcpp::Any visitClassBodyDeclaration0(JavaLabeledParser::ClassBodyDeclaration0Context *ctx);

    antlrcpp::Any visitClassBodyDeclaration2(JavaLabeledParser::ClassBodyDeclaration2Context *ctx);

    antlrcpp::Any visitMemberDeclaration8(JavaLabeledParser::MemberDeclaration8Context *ctx);

    antlrcpp::Any visitMemberDeclaration0(JavaLabeledParser::MemberDeclaration0Context *ctx);

    antlrcpp::Any visitMemberDeclaration1(JavaLabeledParser::MemberDeclaration1Context *ctx);

    antlrcpp::Any visitMemberDeclaration2(JavaLabeledParser::MemberDeclaration2Context *ctx);

    antlrcpp::Any visitMemberDeclaration3(JavaLabeledParser::MemberDeclaration3Context *ctx);

    antlrcpp::Any visitMemberDeclaration4(JavaLabeledParser::MemberDeclaration4Context *ctx);

    antlrcpp::Any visitMemberDeclaration5(JavaLabeledParser::MemberDeclaration5Context *ctx);

    antlrcpp::Any visitMemberDeclaration6(JavaLabeledParser::MemberDeclaration6Context *ctx);

    antlrcpp::Any visitMemberDeclaration7(JavaLabeledParser::MemberDeclaration7Context *ctx);

    antlrcpp::Any visitMethodDeclaration(JavaLabeledParser::MethodDeclarationContext *ctx);

    antlrcpp::Any visitMethodBody(JavaLabeledParser::MethodBodyContext *ctx);

    antlrcpp::Any visitTypeTypeOrVoid(JavaLabeledParser::TypeTypeOrVoidContext *ctx);

    antlrcpp::Any visitGenericMethodDeclaration(JavaLabeledParser::GenericMethodDeclarationContext *ctx);

    antlrcpp::Any visitGenericConstructorDeclaration(JavaLabeledParser::GenericConstructorDeclarationContext *ctx);

    antlrcpp::Any visitConstructorDeclaration(JavaLabeledParser::ConstructorDeclarationContext *ctx);

    antlrcpp::Any visitFieldDeclaration(JavaLabeledParser::FieldDeclarationContext *ctx);

    antlrcpp::Any visitInterfaceBodyDeclaration(JavaLabeledParser::InterfaceBodyDeclarationContext *ctx);

    antlrcpp::Any visitInterfaceMemberDeclaration6(JavaLabeledParser::InterfaceMemberDeclaration6Context *ctx);

    antlrcpp::Any visitInterfaceMemberDeclaration5(JavaLabeledParser::InterfaceMemberDeclaration5Context *ctx);

    antlrcpp::Any visitInterfaceMemberDeclaration4(JavaLabeledParser::InterfaceMemberDeclaration4Context *ctx);

    antlrcpp::Any visitInterfaceMemberDeclaration3(JavaLabeledParser::InterfaceMemberDeclaration3Context *ctx);

    antlrcpp::Any visitInterfaceMemberDeclaration2(JavaLabeledParser::InterfaceMemberDeclaration2Context *ctx);

    antlrcpp::Any visitInterfaceMemberDeclaration1(JavaLabeledParser::InterfaceMemberDeclaration1Context *ctx);

    antlrcpp::Any visitInterfaceMemberDeclaration0(JavaLabeledParser::InterfaceMemberDeclaration0Context *ctx);

    antlrcpp::Any visitConstDeclaration(JavaLabeledParser::ConstDeclarationContext *ctx);

    antlrcpp::Any visitConstantDeclarator(JavaLabeledParser::ConstantDeclaratorContext *ctx);

    antlrcpp::Any visitInterfaceMethodDeclaration(JavaLabeledParser::InterfaceMethodDeclarationContext *ctx);

    antlrcpp::Any visitInterfaceMethodModifier(JavaLabeledParser::InterfaceMethodModifierContext *ctx);

    antlrcpp::Any visitGenericInterfaceMethodDeclaration(JavaLabeledParser::GenericInterfaceMethodDeclarationContext *ctx);

    antlrcpp::Any visitVariableDeclarators(JavaLabeledParser::VariableDeclaratorsContext *ctx);

    antlrcpp::Any visitVariableDeclarator(JavaLabeledParser::VariableDeclaratorContext *ctx);

    antlrcpp::Any visitVariableDeclaratorId(JavaLabeledParser::VariableDeclaratorIdContext *ctx);

    antlrcpp::Any visitVariableInitializer1(JavaLabeledParser::VariableInitializer1Context *ctx);

    antlrcpp::Any visitVariableInitializer0(JavaLabeledParser::VariableInitializer0Context *ctx);

    antlrcpp::Any visitArrayInitializer(JavaLabeledParser::ArrayInitializerContext *ctx);

    antlrcpp::Any visitClassOrInterfaceType(JavaLabeledParser::ClassOrInterfaceTypeContext *ctx);

    antlrcpp::Any visitTypeArgument0(JavaLabeledParser::TypeArgument0Context *ctx);

    antlrcpp::Any visitQualifiedNameList(JavaLabeledParser::QualifiedNameListContext *ctx);

    antlrcpp::Any visitFormalParameters(JavaLabeledParser::FormalParametersContext *ctx);

    antlrcpp::Any visitFormalParameterList1(JavaLabeledParser::FormalParameterList1Context *ctx);

    antlrcpp::Any visitFormalParameterList0(JavaLabeledParser::FormalParameterList0Context *ctx);

    antlrcpp::Any visitFormalParameter(JavaLabeledParser::FormalParameterContext *ctx);

    antlrcpp::Any visitLastFormalParameter(JavaLabeledParser::LastFormalParameterContext *ctx);

    antlrcpp::Any visitQualifiedName(JavaLabeledParser::QualifiedNameContext *ctx);

    antlrcpp::Any visitLiteral2(JavaLabeledParser::Literal2Context *ctx);

    antlrcpp::Any visitLiteral1(JavaLabeledParser::Literal1Context *ctx);

    antlrcpp::Any visitLiteral0(JavaLabeledParser::Literal0Context *ctx);

    antlrcpp::Any visitLiteral5(JavaLabeledParser::Literal5Context *ctx);

    antlrcpp::Any visitLiteral4(JavaLabeledParser::Literal4Context *ctx);

    antlrcpp::Any visitLiteral3(JavaLabeledParser::Literal3Context *ctx);

    antlrcpp::Any visitIntegerLiteral(JavaLabeledParser::IntegerLiteralContext *ctx);

    antlrcpp::Any visitFloatLiteral(JavaLabeledParser::FloatLiteralContext *ctx);

    antlrcpp::Any visitAltAnnotationQualifiedName(JavaLabeledParser::AltAnnotationQualifiedNameContext *ctx);

    antlrcpp::Any visitAnnotation(JavaLabeledParser::AnnotationContext *ctx);

    antlrcpp::Any visitElementValuePairs(JavaLabeledParser::ElementValuePairsContext *ctx);

    antlrcpp::Any visitElementValuePair(JavaLabeledParser::ElementValuePairContext *ctx);

    antlrcpp::Any visitElementValue0(JavaLabeledParser::ElementValue0Context *ctx);

    antlrcpp::Any visitElementValue2(JavaLabeledParser::ElementValue2Context *ctx);

    antlrcpp::Any visitElementValue1(JavaLabeledParser::ElementValue1Context *ctx);

    antlrcpp::Any visitElementValueArrayInitializer(JavaLabeledParser::ElementValueArrayInitializerContext *ctx);

    antlrcpp::Any visitAnnotationTypeDeclaration(JavaLabeledParser::AnnotationTypeDeclarationContext *ctx);

    antlrcpp::Any visitAnnotationTypeBody(JavaLabeledParser::AnnotationTypeBodyContext *ctx);

    antlrcpp::Any visitAnnotationTypeElementDeclaration(JavaLabeledParser::AnnotationTypeElementDeclarationContext *ctx);

    antlrcpp::Any visitAnnotationTypeElementRest0(JavaLabeledParser::AnnotationTypeElementRest0Context *ctx);

    antlrcpp::Any visitAnnotationTypeElementRest1(JavaLabeledParser::AnnotationTypeElementRest1Context *ctx);

    antlrcpp::Any visitAnnotationTypeElementRest2(JavaLabeledParser::AnnotationTypeElementRest2Context *ctx);

    antlrcpp::Any visitAnnotationTypeElementRest3(JavaLabeledParser::AnnotationTypeElementRest3Context *ctx);

    antlrcpp::Any visitAnnotationTypeElementRest4(JavaLabeledParser::AnnotationTypeElementRest4Context *ctx);

    antlrcpp::Any visitAnnotationMethodOrConstantRest0(JavaLabeledParser::AnnotationMethodOrConstantRest0Context *ctx);

    antlrcpp::Any visitAnnotationMethodOrConstantRest1(JavaLabeledParser::AnnotationMethodOrConstantRest1Context *ctx);

    antlrcpp::Any visitAnnotationMethodRest(JavaLabeledParser::AnnotationMethodRestContext *ctx);

    antlrcpp::Any visitAnnotationConstantRest(JavaLabeledParser::AnnotationConstantRestContext *ctx);

    antlrcpp::Any visitDefaultValue(JavaLabeledParser::DefaultValueContext *ctx);

    antlrcpp::Any visitBlock(JavaLabeledParser::BlockContext *ctx);

    antlrcpp::Any visitBlockStatement1(JavaLabeledParser::BlockStatement1Context *ctx);

    antlrcpp::Any visitBlockStatement0(JavaLabeledParser::BlockStatement0Context *ctx);

    antlrcpp::Any visitBlockStatement2(JavaLabeledParser::BlockStatement2Context *ctx);

    antlrcpp::Any visitLocalVariableDeclaration(JavaLabeledParser::LocalVariableDeclarationContext *ctx);

    antlrcpp::Any visitLocalTypeDeclaration(JavaLabeledParser::LocalTypeDeclarationContext *ctx);

    antlrcpp::Any visitStatement14(JavaLabeledParser::Statement14Context *ctx);

    antlrcpp::Any visitStatement15(JavaLabeledParser::Statement15Context *ctx);

    antlrcpp::Any visitStatement12(JavaLabeledParser::Statement12Context *ctx);

    antlrcpp::Any visitStatement13(JavaLabeledParser::Statement13Context *ctx);

    antlrcpp::Any visitStatement9(JavaLabeledParser::Statement9Context *ctx);

    antlrcpp::Any visitStatement7(JavaLabeledParser::Statement7Context *ctx);

    antlrcpp::Any visitStatement16(JavaLabeledParser::Statement16Context *ctx);

    antlrcpp::Any visitStatement8(JavaLabeledParser::Statement8Context *ctx);

    antlrcpp::Any visitStatement5(JavaLabeledParser::Statement5Context *ctx);

    antlrcpp::Any visitStatement6(JavaLabeledParser::Statement6Context *ctx);

    antlrcpp::Any visitStatement3(JavaLabeledParser::Statement3Context *ctx);

    antlrcpp::Any visitStatement4(JavaLabeledParser::Statement4Context *ctx);

    antlrcpp::Any visitStatement1(JavaLabeledParser::Statement1Context *ctx);

    antlrcpp::Any visitStatement2(JavaLabeledParser::Statement2Context *ctx);

    antlrcpp::Any visitStatement0(JavaLabeledParser::Statement0Context *ctx);

    antlrcpp::Any visitStatement10(JavaLabeledParser::Statement10Context *ctx);

    antlrcpp::Any visitStatement11(JavaLabeledParser::Statement11Context *ctx);

    antlrcpp::Any visitCatchClause(JavaLabeledParser::CatchClauseContext *ctx);

    antlrcpp::Any visitCatchType(JavaLabeledParser::CatchTypeContext *ctx);

    antlrcpp::Any visitFinallyBlock(JavaLabeledParser::FinallyBlockContext *ctx);

    antlrcpp::Any visitResourceSpecification(JavaLabeledParser::ResourceSpecificationContext *ctx);

    antlrcpp::Any visitResources(JavaLabeledParser::ResourcesContext *ctx);

    antlrcpp::Any visitResource(JavaLabeledParser::ResourceContext *ctx);

    antlrcpp::Any visitSwitchBlockStatementGroup(JavaLabeledParser::SwitchBlockStatementGroupContext *ctx);

    antlrcpp::Any visitSwitchLabel(JavaLabeledParser::SwitchLabelContext *ctx);

    antlrcpp::Any visitForControl0(JavaLabeledParser::ForControl0Context *ctx);

    antlrcpp::Any visitForControl1(JavaLabeledParser::ForControl1Context *ctx);

    antlrcpp::Any visitForInit1(JavaLabeledParser::ForInit1Context *ctx);

    antlrcpp::Any visitForInit0(JavaLabeledParser::ForInit0Context *ctx);

    antlrcpp::Any visitEnhancedForControl(JavaLabeledParser::EnhancedForControlContext *ctx);

    antlrcpp::Any visitParExpression(JavaLabeledParser::ParExpressionContext *ctx);

    antlrcpp::Any visitExpressionList(JavaLabeledParser::ExpressionListContext *ctx);

    antlrcpp::Any visitMethodCall0(JavaLabeledParser::MethodCall0Context *ctx);

    antlrcpp::Any visitMethodCall1(JavaLabeledParser::MethodCall1Context *ctx);

    antlrcpp::Any visitMethodCall2(JavaLabeledParser::MethodCall2Context *ctx);

    antlrcpp::Any visitExpression8(JavaLabeledParser::Expression8Context *ctx);

    antlrcpp::Any visitExpression10(JavaLabeledParser::Expression10Context *ctx);

    antlrcpp::Any visitExpression9(JavaLabeledParser::Expression9Context *ctx);

    antlrcpp::Any visitExpression12(JavaLabeledParser::Expression12Context *ctx);

    antlrcpp::Any visitExpression11(JavaLabeledParser::Expression11Context *ctx);

    antlrcpp::Any visitExpression14(JavaLabeledParser::Expression14Context *ctx);

    antlrcpp::Any visitExpression13(JavaLabeledParser::Expression13Context *ctx);

    antlrcpp::Any visitExpression16(JavaLabeledParser::Expression16Context *ctx);

    antlrcpp::Any visitExpression15(JavaLabeledParser::Expression15Context *ctx);

    antlrcpp::Any visitExpression18(JavaLabeledParser::Expression18Context *ctx);

    antlrcpp::Any visitExpression17(JavaLabeledParser::Expression17Context *ctx);

    antlrcpp::Any visitExpression19(JavaLabeledParser::Expression19Context *ctx);

    antlrcpp::Any visitExpression6(JavaLabeledParser::Expression6Context *ctx);

    antlrcpp::Any visitExpression7(JavaLabeledParser::Expression7Context *ctx);

    antlrcpp::Any visitExpression4(JavaLabeledParser::Expression4Context *ctx);

    antlrcpp::Any visitExpression5(JavaLabeledParser::Expression5Context *ctx);

    antlrcpp::Any visitExpression2(JavaLabeledParser::Expression2Context *ctx);

    antlrcpp::Any visitExpression3(JavaLabeledParser::Expression3Context *ctx);

    antlrcpp::Any visitExpression0(JavaLabeledParser::Expression0Context *ctx);

    antlrcpp::Any visitExpression1(JavaLabeledParser::Expression1Context *ctx);

    antlrcpp::Any visitExpression21(JavaLabeledParser::Expression21Context *ctx);

    antlrcpp::Any visitExpression20(JavaLabeledParser::Expression20Context *ctx);

    antlrcpp::Any visitExpression23(JavaLabeledParser::Expression23Context *ctx);

    antlrcpp::Any visitExpression22(JavaLabeledParser::Expression22Context *ctx);

    antlrcpp::Any visitExpression25(JavaLabeledParser::Expression25Context *ctx);

    antlrcpp::Any visitExpression24(JavaLabeledParser::Expression24Context *ctx);

    antlrcpp::Any visitLambdaExpression(JavaLabeledParser::LambdaExpressionContext *ctx);

    antlrcpp::Any visitLambdaParameters0(JavaLabeledParser::LambdaParameters0Context *ctx);

    antlrcpp::Any visitLambdaParameters1(JavaLabeledParser::LambdaParameters1Context *ctx);

    antlrcpp::Any visitLambdaParameters2(JavaLabeledParser::LambdaParameters2Context *ctx);

    antlrcpp::Any visitLambdaBody0(JavaLabeledParser::LambdaBody0Context *ctx);

    antlrcpp::Any visitLambdaBody1(JavaLabeledParser::LambdaBody1Context *ctx);

    antlrcpp::Any visitPrimary6(JavaLabeledParser::Primary6Context *ctx);

    antlrcpp::Any visitPrimary2(JavaLabeledParser::Primary2Context *ctx);

    antlrcpp::Any visitPrimary3(JavaLabeledParser::Primary3Context *ctx);

    antlrcpp::Any visitPrimary4(JavaLabeledParser::Primary4Context *ctx);

    antlrcpp::Any visitPrimary5(JavaLabeledParser::Primary5Context *ctx);

    antlrcpp::Any visitPrimary0(JavaLabeledParser::Primary0Context *ctx);

    antlrcpp::Any visitPrimary1(JavaLabeledParser::Primary1Context *ctx);

    antlrcpp::Any visitClassType(JavaLabeledParser::ClassTypeContext *ctx);

    antlrcpp::Any visitCreator1(JavaLabeledParser::Creator1Context *ctx);

    antlrcpp::Any visitCreator0(JavaLabeledParser::Creator0Context *ctx);

    antlrcpp::Any visitCreatedName0(JavaLabeledParser::CreatedName0Context *ctx);

    antlrcpp::Any visitCreatedName1(JavaLabeledParser::CreatedName1Context *ctx);

    antlrcpp::Any visitInnerCreator(JavaLabeledParser::InnerCreatorContext *ctx);

    antlrcpp::Any visitArrayCreatorRest(JavaLabeledParser::ArrayCreatorRestContext *ctx);

    antlrcpp::Any visitClassCreatorRest(JavaLabeledParser::ClassCreatorRestContext *ctx);

    antlrcpp::Any visitExplicitGenericInvocation(JavaLabeledParser::ExplicitGenericInvocationContext *ctx);

    antlrcpp::Any visitTypeArgumentsOrDiamond(JavaLabeledParser::TypeArgumentsOrDiamondContext *ctx);

    antlrcpp::Any visitNonWildcardTypeArgumentsOrDiamond(JavaLabeledParser::NonWildcardTypeArgumentsOrDiamondContext *ctx);

    antlrcpp::Any visitNonWildcardTypeArguments(JavaLabeledParser::NonWildcardTypeArgumentsContext *ctx);

    antlrcpp::Any visitTypeList(JavaLabeledParser::TypeListContext *ctx);

    antlrcpp::Any visitTypeType(JavaLabeledParser::TypeTypeContext *ctx);

    antlrcpp::Any visitPrimitiveType(JavaLabeledParser::PrimitiveTypeContext *ctx);

    antlrcpp::Any visitTypeArguments(JavaLabeledParser::TypeArgumentsContext *ctx);

    antlrcpp::Any visitSuperSuffix1(JavaLabeledParser::SuperSuffix1Context *ctx);

    antlrcpp::Any visitSuperSuffix0(JavaLabeledParser::SuperSuffix0Context *ctx);

    antlrcpp::Any visitExplicitGenericInvocationSuffix0(JavaLabeledParser::ExplicitGenericInvocationSuffix0Context *ctx);

    antlrcpp::Any visitExplicitGenericInvocationSuffix1(JavaLabeledParser::ExplicitGenericInvocationSuffix1Context *ctx);

    antlrcpp::Any visitArguments(JavaLabeledParser::ArgumentsContext *ctx);

};