# Generated by Django 3.2.3 on 2021-05-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('data_type', models.CharField(choices=[('int', 'Integer'), ('float', 'Float'), ('str', 'String'), ('bool', 'Boolean'), ('list', 'List')], max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Refactoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('map_string', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('input_example', models.TextField(blank=True, null=True)),
                ('output_example', models.TextField(blank=True, null=True)),
                ('has_example', models.BooleanField(default=True)),
                ('has_description', models.BooleanField(default=True)),
                ('parameters', models.ManyToManyField(to='index.Parameter')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
    ]
