/*
 * This file was auto-generated by speedy-antlr-tool v1.1.0
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#pragma once

#include "JavaParserLabeledBaseVisitor.h"
#include "speedy_antlr.h"

class SA_JavaLabeledTranslator : public JavaParserLabeledBaseVisitor {
    speedy_antlr::Translator *translator;

    // Cached context classes
    PyObject *CompilationUnitContext_cls = NULL;
    PyObject *PackageDeclarationContext_cls = NULL;
    PyObject *ImportDeclarationContext_cls = NULL;
    PyObject *TypeDeclarationContext_cls = NULL;
    PyObject *ModifierContext_cls = NULL;
    PyObject *ClassOrInterfaceModifierContext_cls = NULL;
    PyObject *VariableModifierContext_cls = NULL;
    PyObject *ClassDeclarationContext_cls = NULL;
    PyObject *TypeParametersContext_cls = NULL;
    PyObject *TypeParameterContext_cls = NULL;
    PyObject *TypeBoundContext_cls = NULL;
    PyObject *EnumDeclarationContext_cls = NULL;
    PyObject *EnumConstantsContext_cls = NULL;
    PyObject *EnumConstantContext_cls = NULL;
    PyObject *EnumBodyDeclarationsContext_cls = NULL;
    PyObject *InterfaceDeclarationContext_cls = NULL;
    PyObject *ClassBodyContext_cls = NULL;
    PyObject *InterfaceBodyContext_cls = NULL;
    PyObject *ClassBodyDeclaration1Context_cls = NULL;
    PyObject *ClassBodyDeclaration0Context_cls = NULL;
    PyObject *ClassBodyDeclaration2Context_cls = NULL;
    PyObject *MemberDeclaration8Context_cls = NULL;
    PyObject *MemberDeclaration0Context_cls = NULL;
    PyObject *MemberDeclaration1Context_cls = NULL;
    PyObject *MemberDeclaration2Context_cls = NULL;
    PyObject *MemberDeclaration3Context_cls = NULL;
    PyObject *MemberDeclaration4Context_cls = NULL;
    PyObject *MemberDeclaration5Context_cls = NULL;
    PyObject *MemberDeclaration6Context_cls = NULL;
    PyObject *MemberDeclaration7Context_cls = NULL;
    PyObject *MethodDeclarationContext_cls = NULL;
    PyObject *MethodBodyContext_cls = NULL;
    PyObject *TypeTypeOrVoidContext_cls = NULL;
    PyObject *GenericMethodDeclarationContext_cls = NULL;
    PyObject *GenericConstructorDeclarationContext_cls = NULL;
    PyObject *ConstructorDeclarationContext_cls = NULL;
    PyObject *FieldDeclarationContext_cls = NULL;
    PyObject *InterfaceBodyDeclarationContext_cls = NULL;
    PyObject *InterfaceMemberDeclaration6Context_cls = NULL;
    PyObject *InterfaceMemberDeclaration5Context_cls = NULL;
    PyObject *InterfaceMemberDeclaration4Context_cls = NULL;
    PyObject *InterfaceMemberDeclaration3Context_cls = NULL;
    PyObject *InterfaceMemberDeclaration2Context_cls = NULL;
    PyObject *InterfaceMemberDeclaration1Context_cls = NULL;
    PyObject *InterfaceMemberDeclaration0Context_cls = NULL;
    PyObject *ConstDeclarationContext_cls = NULL;
    PyObject *ConstantDeclaratorContext_cls = NULL;
    PyObject *InterfaceMethodDeclarationContext_cls = NULL;
    PyObject *InterfaceMethodModifierContext_cls = NULL;
    PyObject *GenericInterfaceMethodDeclarationContext_cls = NULL;
    PyObject *VariableDeclaratorsContext_cls = NULL;
    PyObject *VariableDeclaratorContext_cls = NULL;
    PyObject *VariableDeclaratorIdContext_cls = NULL;
    PyObject *VariableInitializer1Context_cls = NULL;
    PyObject *VariableInitializer0Context_cls = NULL;
    PyObject *ArrayInitializerContext_cls = NULL;
    PyObject *ClassOrInterfaceTypeContext_cls = NULL;
    PyObject *TypeArgument0Context_cls = NULL;
    PyObject *QualifiedNameListContext_cls = NULL;
    PyObject *FormalParametersContext_cls = NULL;
    PyObject *FormalParameterList1Context_cls = NULL;
    PyObject *FormalParameterList0Context_cls = NULL;
    PyObject *FormalParameterContext_cls = NULL;
    PyObject *LastFormalParameterContext_cls = NULL;
    PyObject *QualifiedNameContext_cls = NULL;
    PyObject *Literal2Context_cls = NULL;
    PyObject *Literal1Context_cls = NULL;
    PyObject *Literal0Context_cls = NULL;
    PyObject *Literal5Context_cls = NULL;
    PyObject *Literal4Context_cls = NULL;
    PyObject *Literal3Context_cls = NULL;
    PyObject *IntegerLiteralContext_cls = NULL;
    PyObject *FloatLiteralContext_cls = NULL;
    PyObject *AltAnnotationQualifiedNameContext_cls = NULL;
    PyObject *AnnotationContext_cls = NULL;
    PyObject *ElementValuePairsContext_cls = NULL;
    PyObject *ElementValuePairContext_cls = NULL;
    PyObject *ElementValue0Context_cls = NULL;
    PyObject *ElementValue2Context_cls = NULL;
    PyObject *ElementValue1Context_cls = NULL;
    PyObject *ElementValueArrayInitializerContext_cls = NULL;
    PyObject *AnnotationTypeDeclarationContext_cls = NULL;
    PyObject *AnnotationTypeBodyContext_cls = NULL;
    PyObject *AnnotationTypeElementDeclarationContext_cls = NULL;
    PyObject *AnnotationTypeElementRest0Context_cls = NULL;
    PyObject *AnnotationTypeElementRest1Context_cls = NULL;
    PyObject *AnnotationTypeElementRest2Context_cls = NULL;
    PyObject *AnnotationTypeElementRest3Context_cls = NULL;
    PyObject *AnnotationTypeElementRest4Context_cls = NULL;
    PyObject *AnnotationMethodOrConstantRest0Context_cls = NULL;
    PyObject *AnnotationMethodOrConstantRest1Context_cls = NULL;
    PyObject *AnnotationMethodRestContext_cls = NULL;
    PyObject *AnnotationConstantRestContext_cls = NULL;
    PyObject *DefaultValueContext_cls = NULL;
    PyObject *BlockContext_cls = NULL;
    PyObject *BlockStatement1Context_cls = NULL;
    PyObject *BlockStatement0Context_cls = NULL;
    PyObject *BlockStatement2Context_cls = NULL;
    PyObject *LocalVariableDeclarationContext_cls = NULL;
    PyObject *LocalTypeDeclarationContext_cls = NULL;
    PyObject *Statement14Context_cls = NULL;
    PyObject *Statement15Context_cls = NULL;
    PyObject *Statement12Context_cls = NULL;
    PyObject *Statement13Context_cls = NULL;
    PyObject *Statement9Context_cls = NULL;
    PyObject *Statement7Context_cls = NULL;
    PyObject *Statement16Context_cls = NULL;
    PyObject *Statement8Context_cls = NULL;
    PyObject *Statement5Context_cls = NULL;
    PyObject *Statement6Context_cls = NULL;
    PyObject *Statement3Context_cls = NULL;
    PyObject *Statement4Context_cls = NULL;
    PyObject *Statement1Context_cls = NULL;
    PyObject *Statement2Context_cls = NULL;
    PyObject *Statement0Context_cls = NULL;
    PyObject *Statement10Context_cls = NULL;
    PyObject *Statement11Context_cls = NULL;
    PyObject *CatchClauseContext_cls = NULL;
    PyObject *CatchTypeContext_cls = NULL;
    PyObject *FinallyBlockContext_cls = NULL;
    PyObject *ResourceSpecificationContext_cls = NULL;
    PyObject *ResourcesContext_cls = NULL;
    PyObject *ResourceContext_cls = NULL;
    PyObject *SwitchBlockStatementGroupContext_cls = NULL;
    PyObject *SwitchLabelContext_cls = NULL;
    PyObject *ForControl0Context_cls = NULL;
    PyObject *ForControl1Context_cls = NULL;
    PyObject *ForInit1Context_cls = NULL;
    PyObject *ForInit0Context_cls = NULL;
    PyObject *EnhancedForControlContext_cls = NULL;
    PyObject *ParExpressionContext_cls = NULL;
    PyObject *ExpressionListContext_cls = NULL;
    PyObject *MethodCall0Context_cls = NULL;
    PyObject *MethodCall1Context_cls = NULL;
    PyObject *MethodCall2Context_cls = NULL;
    PyObject *Expression8Context_cls = NULL;
    PyObject *Expression10Context_cls = NULL;
    PyObject *Expression9Context_cls = NULL;
    PyObject *Expression12Context_cls = NULL;
    PyObject *Expression11Context_cls = NULL;
    PyObject *Expression14Context_cls = NULL;
    PyObject *Expression13Context_cls = NULL;
    PyObject *Expression16Context_cls = NULL;
    PyObject *Expression15Context_cls = NULL;
    PyObject *Expression18Context_cls = NULL;
    PyObject *Expression17Context_cls = NULL;
    PyObject *Expression19Context_cls = NULL;
    PyObject *Expression6Context_cls = NULL;
    PyObject *Expression7Context_cls = NULL;
    PyObject *Expression4Context_cls = NULL;
    PyObject *Expression5Context_cls = NULL;
    PyObject *Expression2Context_cls = NULL;
    PyObject *Expression3Context_cls = NULL;
    PyObject *Expression0Context_cls = NULL;
    PyObject *Expression1Context_cls = NULL;
    PyObject *Expression21Context_cls = NULL;
    PyObject *Expression20Context_cls = NULL;
    PyObject *Expression23Context_cls = NULL;
    PyObject *Expression22Context_cls = NULL;
    PyObject *Expression25Context_cls = NULL;
    PyObject *Expression24Context_cls = NULL;
    PyObject *LambdaExpressionContext_cls = NULL;
    PyObject *LambdaParameters0Context_cls = NULL;
    PyObject *LambdaParameters1Context_cls = NULL;
    PyObject *LambdaParameters2Context_cls = NULL;
    PyObject *LambdaBody0Context_cls = NULL;
    PyObject *LambdaBody1Context_cls = NULL;
    PyObject *Primary6Context_cls = NULL;
    PyObject *Primary2Context_cls = NULL;
    PyObject *Primary3Context_cls = NULL;
    PyObject *Primary4Context_cls = NULL;
    PyObject *Primary5Context_cls = NULL;
    PyObject *Primary0Context_cls = NULL;
    PyObject *Primary1Context_cls = NULL;
    PyObject *ClassTypeContext_cls = NULL;
    PyObject *Creator1Context_cls = NULL;
    PyObject *Creator0Context_cls = NULL;
    PyObject *CreatedName0Context_cls = NULL;
    PyObject *CreatedName1Context_cls = NULL;
    PyObject *InnerCreatorContext_cls = NULL;
    PyObject *ArrayCreatorRestContext_cls = NULL;
    PyObject *ClassCreatorRestContext_cls = NULL;
    PyObject *ExplicitGenericInvocationContext_cls = NULL;
    PyObject *TypeArgumentsOrDiamondContext_cls = NULL;
    PyObject *NonWildcardTypeArgumentsOrDiamondContext_cls = NULL;
    PyObject *NonWildcardTypeArgumentsContext_cls = NULL;
    PyObject *TypeListContext_cls = NULL;
    PyObject *TypeTypeContext_cls = NULL;
    PyObject *PrimitiveTypeContext_cls = NULL;
    PyObject *TypeArgumentsContext_cls = NULL;
    PyObject *SuperSuffix1Context_cls = NULL;
    PyObject *SuperSuffix0Context_cls = NULL;
    PyObject *ExplicitGenericInvocationSuffix0Context_cls = NULL;
    PyObject *ExplicitGenericInvocationSuffix1Context_cls = NULL;
    PyObject *ArgumentsContext_cls = NULL;

    public:
    SA_JavaLabeledTranslator(speedy_antlr::Translator *translator);
    ~SA_JavaLabeledTranslator();
    antlrcpp::Any visitCompilationUnit(JavaParserLabeled::CompilationUnitContext *ctx);

    antlrcpp::Any visitPackageDeclaration(JavaParserLabeled::PackageDeclarationContext *ctx);

    antlrcpp::Any visitImportDeclaration(JavaParserLabeled::ImportDeclarationContext *ctx);

    antlrcpp::Any visitTypeDeclaration(JavaParserLabeled::TypeDeclarationContext *ctx);

    antlrcpp::Any visitModifier(JavaParserLabeled::ModifierContext *ctx);

    antlrcpp::Any visitClassOrInterfaceModifier(JavaParserLabeled::ClassOrInterfaceModifierContext *ctx);

    antlrcpp::Any visitVariableModifier(JavaParserLabeled::VariableModifierContext *ctx);

    antlrcpp::Any visitClassDeclaration(JavaParserLabeled::ClassDeclarationContext *ctx);

    antlrcpp::Any visitTypeParameters(JavaParserLabeled::TypeParametersContext *ctx);

    antlrcpp::Any visitTypeParameter(JavaParserLabeled::TypeParameterContext *ctx);

    antlrcpp::Any visitTypeBound(JavaParserLabeled::TypeBoundContext *ctx);

    antlrcpp::Any visitEnumDeclaration(JavaParserLabeled::EnumDeclarationContext *ctx);

    antlrcpp::Any visitEnumConstants(JavaParserLabeled::EnumConstantsContext *ctx);

    antlrcpp::Any visitEnumConstant(JavaParserLabeled::EnumConstantContext *ctx);

    antlrcpp::Any visitEnumBodyDeclarations(JavaParserLabeled::EnumBodyDeclarationsContext *ctx);

    antlrcpp::Any visitInterfaceDeclaration(JavaParserLabeled::InterfaceDeclarationContext *ctx);

    antlrcpp::Any visitClassBody(JavaParserLabeled::ClassBodyContext *ctx);

    antlrcpp::Any visitInterfaceBody(JavaParserLabeled::InterfaceBodyContext *ctx);

    antlrcpp::Any visitClassBodyDeclaration1(JavaParserLabeled::ClassBodyDeclaration1Context *ctx);

    antlrcpp::Any visitClassBodyDeclaration0(JavaParserLabeled::ClassBodyDeclaration0Context *ctx);

    antlrcpp::Any visitClassBodyDeclaration2(JavaParserLabeled::ClassBodyDeclaration2Context *ctx);

    antlrcpp::Any visitMemberDeclaration8(JavaParserLabeled::MemberDeclaration8Context *ctx);

    antlrcpp::Any visitMemberDeclaration0(JavaParserLabeled::MemberDeclaration0Context *ctx);

    antlrcpp::Any visitMemberDeclaration1(JavaParserLabeled::MemberDeclaration1Context *ctx);

    antlrcpp::Any visitMemberDeclaration2(JavaParserLabeled::MemberDeclaration2Context *ctx);

    antlrcpp::Any visitMemberDeclaration3(JavaParserLabeled::MemberDeclaration3Context *ctx);

    antlrcpp::Any visitMemberDeclaration4(JavaParserLabeled::MemberDeclaration4Context *ctx);

    antlrcpp::Any visitMemberDeclaration5(JavaParserLabeled::MemberDeclaration5Context *ctx);

    antlrcpp::Any visitMemberDeclaration6(JavaParserLabeled::MemberDeclaration6Context *ctx);

    antlrcpp::Any visitMemberDeclaration7(JavaParserLabeled::MemberDeclaration7Context *ctx);

    antlrcpp::Any visitMethodDeclaration(JavaParserLabeled::MethodDeclarationContext *ctx);

    antlrcpp::Any visitMethodBody(JavaParserLabeled::MethodBodyContext *ctx);

    antlrcpp::Any visitTypeTypeOrVoid(JavaParserLabeled::TypeTypeOrVoidContext *ctx);

    antlrcpp::Any visitGenericMethodDeclaration(JavaParserLabeled::GenericMethodDeclarationContext *ctx);

    antlrcpp::Any visitGenericConstructorDeclaration(JavaParserLabeled::GenericConstructorDeclarationContext *ctx);

    antlrcpp::Any visitConstructorDeclaration(JavaParserLabeled::ConstructorDeclarationContext *ctx);

    antlrcpp::Any visitFieldDeclaration(JavaParserLabeled::FieldDeclarationContext *ctx);

    antlrcpp::Any visitInterfaceBodyDeclaration(JavaParserLabeled::InterfaceBodyDeclarationContext *ctx);

    antlrcpp::Any visitInterfaceMemberDeclaration6(JavaParserLabeled::InterfaceMemberDeclaration6Context *ctx);

    antlrcpp::Any visitInterfaceMemberDeclaration5(JavaParserLabeled::InterfaceMemberDeclaration5Context *ctx);

    antlrcpp::Any visitInterfaceMemberDeclaration4(JavaParserLabeled::InterfaceMemberDeclaration4Context *ctx);

    antlrcpp::Any visitInterfaceMemberDeclaration3(JavaParserLabeled::InterfaceMemberDeclaration3Context *ctx);

    antlrcpp::Any visitInterfaceMemberDeclaration2(JavaParserLabeled::InterfaceMemberDeclaration2Context *ctx);

    antlrcpp::Any visitInterfaceMemberDeclaration1(JavaParserLabeled::InterfaceMemberDeclaration1Context *ctx);

    antlrcpp::Any visitInterfaceMemberDeclaration0(JavaParserLabeled::InterfaceMemberDeclaration0Context *ctx);

    antlrcpp::Any visitConstDeclaration(JavaParserLabeled::ConstDeclarationContext *ctx);

    antlrcpp::Any visitConstantDeclarator(JavaParserLabeled::ConstantDeclaratorContext *ctx);

    antlrcpp::Any visitInterfaceMethodDeclaration(JavaParserLabeled::InterfaceMethodDeclarationContext *ctx);

    antlrcpp::Any visitInterfaceMethodModifier(JavaParserLabeled::InterfaceMethodModifierContext *ctx);

    antlrcpp::Any visitGenericInterfaceMethodDeclaration(JavaParserLabeled::GenericInterfaceMethodDeclarationContext *ctx);

    antlrcpp::Any visitVariableDeclarators(JavaParserLabeled::VariableDeclaratorsContext *ctx);

    antlrcpp::Any visitVariableDeclarator(JavaParserLabeled::VariableDeclaratorContext *ctx);

    antlrcpp::Any visitVariableDeclaratorId(JavaParserLabeled::VariableDeclaratorIdContext *ctx);

    antlrcpp::Any visitVariableInitializer1(JavaParserLabeled::VariableInitializer1Context *ctx);

    antlrcpp::Any visitVariableInitializer0(JavaParserLabeled::VariableInitializer0Context *ctx);

    antlrcpp::Any visitArrayInitializer(JavaParserLabeled::ArrayInitializerContext *ctx);

    antlrcpp::Any visitClassOrInterfaceType(JavaParserLabeled::ClassOrInterfaceTypeContext *ctx);

    antlrcpp::Any visitTypeArgument0(JavaParserLabeled::TypeArgument0Context *ctx);

    antlrcpp::Any visitQualifiedNameList(JavaParserLabeled::QualifiedNameListContext *ctx);

    antlrcpp::Any visitFormalParameters(JavaParserLabeled::FormalParametersContext *ctx);

    antlrcpp::Any visitFormalParameterList1(JavaParserLabeled::FormalParameterList1Context *ctx);

    antlrcpp::Any visitFormalParameterList0(JavaParserLabeled::FormalParameterList0Context *ctx);

    antlrcpp::Any visitFormalParameter(JavaParserLabeled::FormalParameterContext *ctx);

    antlrcpp::Any visitLastFormalParameter(JavaParserLabeled::LastFormalParameterContext *ctx);

    antlrcpp::Any visitQualifiedName(JavaParserLabeled::QualifiedNameContext *ctx);

    antlrcpp::Any visitLiteral2(JavaParserLabeled::Literal2Context *ctx);

    antlrcpp::Any visitLiteral1(JavaParserLabeled::Literal1Context *ctx);

    antlrcpp::Any visitLiteral0(JavaParserLabeled::Literal0Context *ctx);

    antlrcpp::Any visitLiteral5(JavaParserLabeled::Literal5Context *ctx);

    antlrcpp::Any visitLiteral4(JavaParserLabeled::Literal4Context *ctx);

    antlrcpp::Any visitLiteral3(JavaParserLabeled::Literal3Context *ctx);

    antlrcpp::Any visitIntegerLiteral(JavaParserLabeled::IntegerLiteralContext *ctx);

    antlrcpp::Any visitFloatLiteral(JavaParserLabeled::FloatLiteralContext *ctx);

    antlrcpp::Any visitAltAnnotationQualifiedName(JavaParserLabeled::AltAnnotationQualifiedNameContext *ctx);

    antlrcpp::Any visitAnnotation(JavaParserLabeled::AnnotationContext *ctx);

    antlrcpp::Any visitElementValuePairs(JavaParserLabeled::ElementValuePairsContext *ctx);

    antlrcpp::Any visitElementValuePair(JavaParserLabeled::ElementValuePairContext *ctx);

    antlrcpp::Any visitElementValue0(JavaParserLabeled::ElementValue0Context *ctx);

    antlrcpp::Any visitElementValue2(JavaParserLabeled::ElementValue2Context *ctx);

    antlrcpp::Any visitElementValue1(JavaParserLabeled::ElementValue1Context *ctx);

    antlrcpp::Any visitElementValueArrayInitializer(JavaParserLabeled::ElementValueArrayInitializerContext *ctx);

    antlrcpp::Any visitAnnotationTypeDeclaration(JavaParserLabeled::AnnotationTypeDeclarationContext *ctx);

    antlrcpp::Any visitAnnotationTypeBody(JavaParserLabeled::AnnotationTypeBodyContext *ctx);

    antlrcpp::Any visitAnnotationTypeElementDeclaration(JavaParserLabeled::AnnotationTypeElementDeclarationContext *ctx);

    antlrcpp::Any visitAnnotationTypeElementRest0(JavaParserLabeled::AnnotationTypeElementRest0Context *ctx);

    antlrcpp::Any visitAnnotationTypeElementRest1(JavaParserLabeled::AnnotationTypeElementRest1Context *ctx);

    antlrcpp::Any visitAnnotationTypeElementRest2(JavaParserLabeled::AnnotationTypeElementRest2Context *ctx);

    antlrcpp::Any visitAnnotationTypeElementRest3(JavaParserLabeled::AnnotationTypeElementRest3Context *ctx);

    antlrcpp::Any visitAnnotationTypeElementRest4(JavaParserLabeled::AnnotationTypeElementRest4Context *ctx);

    antlrcpp::Any visitAnnotationMethodOrConstantRest0(JavaParserLabeled::AnnotationMethodOrConstantRest0Context *ctx);

    antlrcpp::Any visitAnnotationMethodOrConstantRest1(JavaParserLabeled::AnnotationMethodOrConstantRest1Context *ctx);

    antlrcpp::Any visitAnnotationMethodRest(JavaParserLabeled::AnnotationMethodRestContext *ctx);

    antlrcpp::Any visitAnnotationConstantRest(JavaParserLabeled::AnnotationConstantRestContext *ctx);

    antlrcpp::Any visitDefaultValue(JavaParserLabeled::DefaultValueContext *ctx);

    antlrcpp::Any visitBlock(JavaParserLabeled::BlockContext *ctx);

    antlrcpp::Any visitBlockStatement1(JavaParserLabeled::BlockStatement1Context *ctx);

    antlrcpp::Any visitBlockStatement0(JavaParserLabeled::BlockStatement0Context *ctx);

    antlrcpp::Any visitBlockStatement2(JavaParserLabeled::BlockStatement2Context *ctx);

    antlrcpp::Any visitLocalVariableDeclaration(JavaParserLabeled::LocalVariableDeclarationContext *ctx);

    antlrcpp::Any visitLocalTypeDeclaration(JavaParserLabeled::LocalTypeDeclarationContext *ctx);

    antlrcpp::Any visitStatement14(JavaParserLabeled::Statement14Context *ctx);

    antlrcpp::Any visitStatement15(JavaParserLabeled::Statement15Context *ctx);

    antlrcpp::Any visitStatement12(JavaParserLabeled::Statement12Context *ctx);

    antlrcpp::Any visitStatement13(JavaParserLabeled::Statement13Context *ctx);

    antlrcpp::Any visitStatement9(JavaParserLabeled::Statement9Context *ctx);

    antlrcpp::Any visitStatement7(JavaParserLabeled::Statement7Context *ctx);

    antlrcpp::Any visitStatement16(JavaParserLabeled::Statement16Context *ctx);

    antlrcpp::Any visitStatement8(JavaParserLabeled::Statement8Context *ctx);

    antlrcpp::Any visitStatement5(JavaParserLabeled::Statement5Context *ctx);

    antlrcpp::Any visitStatement6(JavaParserLabeled::Statement6Context *ctx);

    antlrcpp::Any visitStatement3(JavaParserLabeled::Statement3Context *ctx);

    antlrcpp::Any visitStatement4(JavaParserLabeled::Statement4Context *ctx);

    antlrcpp::Any visitStatement1(JavaParserLabeled::Statement1Context *ctx);

    antlrcpp::Any visitStatement2(JavaParserLabeled::Statement2Context *ctx);

    antlrcpp::Any visitStatement0(JavaParserLabeled::Statement0Context *ctx);

    antlrcpp::Any visitStatement10(JavaParserLabeled::Statement10Context *ctx);

    antlrcpp::Any visitStatement11(JavaParserLabeled::Statement11Context *ctx);

    antlrcpp::Any visitCatchClause(JavaParserLabeled::CatchClauseContext *ctx);

    antlrcpp::Any visitCatchType(JavaParserLabeled::CatchTypeContext *ctx);

    antlrcpp::Any visitFinallyBlock(JavaParserLabeled::FinallyBlockContext *ctx);

    antlrcpp::Any visitResourceSpecification(JavaParserLabeled::ResourceSpecificationContext *ctx);

    antlrcpp::Any visitResources(JavaParserLabeled::ResourcesContext *ctx);

    antlrcpp::Any visitResource(JavaParserLabeled::ResourceContext *ctx);

    antlrcpp::Any visitSwitchBlockStatementGroup(JavaParserLabeled::SwitchBlockStatementGroupContext *ctx);

    antlrcpp::Any visitSwitchLabel(JavaParserLabeled::SwitchLabelContext *ctx);

    antlrcpp::Any visitForControl0(JavaParserLabeled::ForControl0Context *ctx);

    antlrcpp::Any visitForControl1(JavaParserLabeled::ForControl1Context *ctx);

    antlrcpp::Any visitForInit1(JavaParserLabeled::ForInit1Context *ctx);

    antlrcpp::Any visitForInit0(JavaParserLabeled::ForInit0Context *ctx);

    antlrcpp::Any visitEnhancedForControl(JavaParserLabeled::EnhancedForControlContext *ctx);

    antlrcpp::Any visitParExpression(JavaParserLabeled::ParExpressionContext *ctx);

    antlrcpp::Any visitExpressionList(JavaParserLabeled::ExpressionListContext *ctx);

    antlrcpp::Any visitMethodCall0(JavaParserLabeled::MethodCall0Context *ctx);

    antlrcpp::Any visitMethodCall1(JavaParserLabeled::MethodCall1Context *ctx);

    antlrcpp::Any visitMethodCall2(JavaParserLabeled::MethodCall2Context *ctx);

    antlrcpp::Any visitExpression8(JavaParserLabeled::Expression8Context *ctx);

    antlrcpp::Any visitExpression10(JavaParserLabeled::Expression10Context *ctx);

    antlrcpp::Any visitExpression9(JavaParserLabeled::Expression9Context *ctx);

    antlrcpp::Any visitExpression12(JavaParserLabeled::Expression12Context *ctx);

    antlrcpp::Any visitExpression11(JavaParserLabeled::Expression11Context *ctx);

    antlrcpp::Any visitExpression14(JavaParserLabeled::Expression14Context *ctx);

    antlrcpp::Any visitExpression13(JavaParserLabeled::Expression13Context *ctx);

    antlrcpp::Any visitExpression16(JavaParserLabeled::Expression16Context *ctx);

    antlrcpp::Any visitExpression15(JavaParserLabeled::Expression15Context *ctx);

    antlrcpp::Any visitExpression18(JavaParserLabeled::Expression18Context *ctx);

    antlrcpp::Any visitExpression17(JavaParserLabeled::Expression17Context *ctx);

    antlrcpp::Any visitExpression19(JavaParserLabeled::Expression19Context *ctx);

    antlrcpp::Any visitExpression6(JavaParserLabeled::Expression6Context *ctx);

    antlrcpp::Any visitExpression7(JavaParserLabeled::Expression7Context *ctx);

    antlrcpp::Any visitExpression4(JavaParserLabeled::Expression4Context *ctx);

    antlrcpp::Any visitExpression5(JavaParserLabeled::Expression5Context *ctx);

    antlrcpp::Any visitExpression2(JavaParserLabeled::Expression2Context *ctx);

    antlrcpp::Any visitExpression3(JavaParserLabeled::Expression3Context *ctx);

    antlrcpp::Any visitExpression0(JavaParserLabeled::Expression0Context *ctx);

    antlrcpp::Any visitExpression1(JavaParserLabeled::Expression1Context *ctx);

    antlrcpp::Any visitExpression21(JavaParserLabeled::Expression21Context *ctx);

    antlrcpp::Any visitExpression20(JavaParserLabeled::Expression20Context *ctx);

    antlrcpp::Any visitExpression23(JavaParserLabeled::Expression23Context *ctx);

    antlrcpp::Any visitExpression22(JavaParserLabeled::Expression22Context *ctx);

    antlrcpp::Any visitExpression25(JavaParserLabeled::Expression25Context *ctx);

    antlrcpp::Any visitExpression24(JavaParserLabeled::Expression24Context *ctx);

    antlrcpp::Any visitLambdaExpression(JavaParserLabeled::LambdaExpressionContext *ctx);

    antlrcpp::Any visitLambdaParameters0(JavaParserLabeled::LambdaParameters0Context *ctx);

    antlrcpp::Any visitLambdaParameters1(JavaParserLabeled::LambdaParameters1Context *ctx);

    antlrcpp::Any visitLambdaParameters2(JavaParserLabeled::LambdaParameters2Context *ctx);

    antlrcpp::Any visitLambdaBody0(JavaParserLabeled::LambdaBody0Context *ctx);

    antlrcpp::Any visitLambdaBody1(JavaParserLabeled::LambdaBody1Context *ctx);

    antlrcpp::Any visitPrimary6(JavaParserLabeled::Primary6Context *ctx);

    antlrcpp::Any visitPrimary2(JavaParserLabeled::Primary2Context *ctx);

    antlrcpp::Any visitPrimary3(JavaParserLabeled::Primary3Context *ctx);

    antlrcpp::Any visitPrimary4(JavaParserLabeled::Primary4Context *ctx);

    antlrcpp::Any visitPrimary5(JavaParserLabeled::Primary5Context *ctx);

    antlrcpp::Any visitPrimary0(JavaParserLabeled::Primary0Context *ctx);

    antlrcpp::Any visitPrimary1(JavaParserLabeled::Primary1Context *ctx);

    antlrcpp::Any visitClassType(JavaParserLabeled::ClassTypeContext *ctx);

    antlrcpp::Any visitCreator1(JavaParserLabeled::Creator1Context *ctx);

    antlrcpp::Any visitCreator0(JavaParserLabeled::Creator0Context *ctx);

    antlrcpp::Any visitCreatedName0(JavaParserLabeled::CreatedName0Context *ctx);

    antlrcpp::Any visitCreatedName1(JavaParserLabeled::CreatedName1Context *ctx);

    antlrcpp::Any visitInnerCreator(JavaParserLabeled::InnerCreatorContext *ctx);

    antlrcpp::Any visitArrayCreatorRest(JavaParserLabeled::ArrayCreatorRestContext *ctx);

    antlrcpp::Any visitClassCreatorRest(JavaParserLabeled::ClassCreatorRestContext *ctx);

    antlrcpp::Any visitExplicitGenericInvocation(JavaParserLabeled::ExplicitGenericInvocationContext *ctx);

    antlrcpp::Any visitTypeArgumentsOrDiamond(JavaParserLabeled::TypeArgumentsOrDiamondContext *ctx);

    antlrcpp::Any visitNonWildcardTypeArgumentsOrDiamond(JavaParserLabeled::NonWildcardTypeArgumentsOrDiamondContext *ctx);

    antlrcpp::Any visitNonWildcardTypeArguments(JavaParserLabeled::NonWildcardTypeArgumentsContext *ctx);

    antlrcpp::Any visitTypeList(JavaParserLabeled::TypeListContext *ctx);

    antlrcpp::Any visitTypeType(JavaParserLabeled::TypeTypeContext *ctx);

    antlrcpp::Any visitPrimitiveType(JavaParserLabeled::PrimitiveTypeContext *ctx);

    antlrcpp::Any visitTypeArguments(JavaParserLabeled::TypeArgumentsContext *ctx);

    antlrcpp::Any visitSuperSuffix1(JavaParserLabeled::SuperSuffix1Context *ctx);

    antlrcpp::Any visitSuperSuffix0(JavaParserLabeled::SuperSuffix0Context *ctx);

    antlrcpp::Any visitExplicitGenericInvocationSuffix0(JavaParserLabeled::ExplicitGenericInvocationSuffix0Context *ctx);

    antlrcpp::Any visitExplicitGenericInvocationSuffix1(JavaParserLabeled::ExplicitGenericInvocationSuffix1Context *ctx);

    antlrcpp::Any visitArguments(JavaParserLabeled::ArgumentsContext *ctx);

};