//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from JavaParserLabeled.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace UndContain {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="JavaParserLabeled"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IJavaParserLabeledVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.compilationUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompilationUnit([NotNull] JavaParserLabeled.CompilationUnitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.packageDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPackageDeclaration([NotNull] JavaParserLabeled.PackageDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.importDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImportDeclaration([NotNull] JavaParserLabeled.ImportDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.typeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeDeclaration([NotNull] JavaParserLabeled.TypeDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModifier([NotNull] JavaParserLabeled.ModifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.classOrInterfaceModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassOrInterfaceModifier([NotNull] JavaParserLabeled.ClassOrInterfaceModifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.variableModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableModifier([NotNull] JavaParserLabeled.VariableModifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.classDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassDeclaration([NotNull] JavaParserLabeled.ClassDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.typeParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeParameters([NotNull] JavaParserLabeled.TypeParametersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.typeParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeParameter([NotNull] JavaParserLabeled.TypeParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.typeBound"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeBound([NotNull] JavaParserLabeled.TypeBoundContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.enumDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumDeclaration([NotNull] JavaParserLabeled.EnumDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.enumConstants"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumConstants([NotNull] JavaParserLabeled.EnumConstantsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.enumConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumConstant([NotNull] JavaParserLabeled.EnumConstantContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.enumBodyDeclarations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumBodyDeclarations([NotNull] JavaParserLabeled.EnumBodyDeclarationsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.interfaceDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceDeclaration([NotNull] JavaParserLabeled.InterfaceDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.classBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassBody([NotNull] JavaParserLabeled.ClassBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.interfaceBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceBody([NotNull] JavaParserLabeled.InterfaceBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>classBodyDeclaration0</c>
	/// labeled alternative in <see cref="JavaParserLabeled.classBodyDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassBodyDeclaration0([NotNull] JavaParserLabeled.ClassBodyDeclaration0Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>classBodyDeclaration1</c>
	/// labeled alternative in <see cref="JavaParserLabeled.classBodyDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassBodyDeclaration1([NotNull] JavaParserLabeled.ClassBodyDeclaration1Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>classBodyDeclaration2</c>
	/// labeled alternative in <see cref="JavaParserLabeled.classBodyDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassBodyDeclaration2([NotNull] JavaParserLabeled.ClassBodyDeclaration2Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>memberDeclaration0</c>
	/// labeled alternative in <see cref="JavaParserLabeled.memberDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemberDeclaration0([NotNull] JavaParserLabeled.MemberDeclaration0Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>memberDeclaration1</c>
	/// labeled alternative in <see cref="JavaParserLabeled.memberDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemberDeclaration1([NotNull] JavaParserLabeled.MemberDeclaration1Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>memberDeclaration2</c>
	/// labeled alternative in <see cref="JavaParserLabeled.memberDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemberDeclaration2([NotNull] JavaParserLabeled.MemberDeclaration2Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>memberDeclaration3</c>
	/// labeled alternative in <see cref="JavaParserLabeled.memberDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemberDeclaration3([NotNull] JavaParserLabeled.MemberDeclaration3Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>memberDeclaration4</c>
	/// labeled alternative in <see cref="JavaParserLabeled.memberDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemberDeclaration4([NotNull] JavaParserLabeled.MemberDeclaration4Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>memberDeclaration5</c>
	/// labeled alternative in <see cref="JavaParserLabeled.memberDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemberDeclaration5([NotNull] JavaParserLabeled.MemberDeclaration5Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>memberDeclaration6</c>
	/// labeled alternative in <see cref="JavaParserLabeled.memberDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemberDeclaration6([NotNull] JavaParserLabeled.MemberDeclaration6Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>memberDeclaration7</c>
	/// labeled alternative in <see cref="JavaParserLabeled.memberDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemberDeclaration7([NotNull] JavaParserLabeled.MemberDeclaration7Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>memberDeclaration8</c>
	/// labeled alternative in <see cref="JavaParserLabeled.memberDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemberDeclaration8([NotNull] JavaParserLabeled.MemberDeclaration8Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.methodDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodDeclaration([NotNull] JavaParserLabeled.MethodDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.methodBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodBody([NotNull] JavaParserLabeled.MethodBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.typeTypeOrVoid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeTypeOrVoid([NotNull] JavaParserLabeled.TypeTypeOrVoidContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.genericMethodDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGenericMethodDeclaration([NotNull] JavaParserLabeled.GenericMethodDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.genericConstructorDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGenericConstructorDeclaration([NotNull] JavaParserLabeled.GenericConstructorDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.constructorDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstructorDeclaration([NotNull] JavaParserLabeled.ConstructorDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.fieldDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldDeclaration([NotNull] JavaParserLabeled.FieldDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.interfaceBodyDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceBodyDeclaration([NotNull] JavaParserLabeled.InterfaceBodyDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>interfaceMemberDeclaration0</c>
	/// labeled alternative in <see cref="JavaParserLabeled.interfaceMemberDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceMemberDeclaration0([NotNull] JavaParserLabeled.InterfaceMemberDeclaration0Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>interfaceMemberDeclaration1</c>
	/// labeled alternative in <see cref="JavaParserLabeled.interfaceMemberDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceMemberDeclaration1([NotNull] JavaParserLabeled.InterfaceMemberDeclaration1Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>interfaceMemberDeclaration2</c>
	/// labeled alternative in <see cref="JavaParserLabeled.interfaceMemberDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceMemberDeclaration2([NotNull] JavaParserLabeled.InterfaceMemberDeclaration2Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>interfaceMemberDeclaration3</c>
	/// labeled alternative in <see cref="JavaParserLabeled.interfaceMemberDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceMemberDeclaration3([NotNull] JavaParserLabeled.InterfaceMemberDeclaration3Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>interfaceMemberDeclaration4</c>
	/// labeled alternative in <see cref="JavaParserLabeled.interfaceMemberDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceMemberDeclaration4([NotNull] JavaParserLabeled.InterfaceMemberDeclaration4Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>interfaceMemberDeclaration5</c>
	/// labeled alternative in <see cref="JavaParserLabeled.interfaceMemberDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceMemberDeclaration5([NotNull] JavaParserLabeled.InterfaceMemberDeclaration5Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>interfaceMemberDeclaration6</c>
	/// labeled alternative in <see cref="JavaParserLabeled.interfaceMemberDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceMemberDeclaration6([NotNull] JavaParserLabeled.InterfaceMemberDeclaration6Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.constDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstDeclaration([NotNull] JavaParserLabeled.ConstDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.constantDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstantDeclarator([NotNull] JavaParserLabeled.ConstantDeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.interfaceMethodDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceMethodDeclaration([NotNull] JavaParserLabeled.InterfaceMethodDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.interfaceMethodModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceMethodModifier([NotNull] JavaParserLabeled.InterfaceMethodModifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.genericInterfaceMethodDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGenericInterfaceMethodDeclaration([NotNull] JavaParserLabeled.GenericInterfaceMethodDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.variableDeclarators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableDeclarators([NotNull] JavaParserLabeled.VariableDeclaratorsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.variableDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableDeclarator([NotNull] JavaParserLabeled.VariableDeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.variableDeclaratorId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableDeclaratorId([NotNull] JavaParserLabeled.VariableDeclaratorIdContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>variableInitializer0</c>
	/// labeled alternative in <see cref="JavaParserLabeled.variableInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableInitializer0([NotNull] JavaParserLabeled.VariableInitializer0Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>variableInitializer1</c>
	/// labeled alternative in <see cref="JavaParserLabeled.variableInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableInitializer1([NotNull] JavaParserLabeled.VariableInitializer1Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.arrayInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayInitializer([NotNull] JavaParserLabeled.ArrayInitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.classOrInterfaceType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassOrInterfaceType([NotNull] JavaParserLabeled.ClassOrInterfaceTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>typeArgument0</c>
	/// labeled alternative in <see cref="JavaParserLabeled.typeArgument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeArgument0([NotNull] JavaParserLabeled.TypeArgument0Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.qualifiedNameList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualifiedNameList([NotNull] JavaParserLabeled.QualifiedNameListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.formalParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFormalParameters([NotNull] JavaParserLabeled.FormalParametersContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>formalParameterList0</c>
	/// labeled alternative in <see cref="JavaParserLabeled.formalParameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFormalParameterList0([NotNull] JavaParserLabeled.FormalParameterList0Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>formalParameterList1</c>
	/// labeled alternative in <see cref="JavaParserLabeled.formalParameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFormalParameterList1([NotNull] JavaParserLabeled.FormalParameterList1Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.formalParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFormalParameter([NotNull] JavaParserLabeled.FormalParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.lastFormalParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLastFormalParameter([NotNull] JavaParserLabeled.LastFormalParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.qualifiedName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualifiedName([NotNull] JavaParserLabeled.QualifiedNameContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>literal0</c>
	/// labeled alternative in <see cref="JavaParserLabeled.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral0([NotNull] JavaParserLabeled.Literal0Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>literal1</c>
	/// labeled alternative in <see cref="JavaParserLabeled.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral1([NotNull] JavaParserLabeled.Literal1Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>literal2</c>
	/// labeled alternative in <see cref="JavaParserLabeled.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral2([NotNull] JavaParserLabeled.Literal2Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>literal3</c>
	/// labeled alternative in <see cref="JavaParserLabeled.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral3([NotNull] JavaParserLabeled.Literal3Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>literal4</c>
	/// labeled alternative in <see cref="JavaParserLabeled.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral4([NotNull] JavaParserLabeled.Literal4Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>literal5</c>
	/// labeled alternative in <see cref="JavaParserLabeled.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral5([NotNull] JavaParserLabeled.Literal5Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.integerLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntegerLiteral([NotNull] JavaParserLabeled.IntegerLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.floatLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFloatLiteral([NotNull] JavaParserLabeled.FloatLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.altAnnotationQualifiedName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAltAnnotationQualifiedName([NotNull] JavaParserLabeled.AltAnnotationQualifiedNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotation([NotNull] JavaParserLabeled.AnnotationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.elementValuePairs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElementValuePairs([NotNull] JavaParserLabeled.ElementValuePairsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.elementValuePair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElementValuePair([NotNull] JavaParserLabeled.ElementValuePairContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>elementValue0</c>
	/// labeled alternative in <see cref="JavaParserLabeled.elementValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElementValue0([NotNull] JavaParserLabeled.ElementValue0Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>elementValue1</c>
	/// labeled alternative in <see cref="JavaParserLabeled.elementValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElementValue1([NotNull] JavaParserLabeled.ElementValue1Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>elementValue2</c>
	/// labeled alternative in <see cref="JavaParserLabeled.elementValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElementValue2([NotNull] JavaParserLabeled.ElementValue2Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.elementValueArrayInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElementValueArrayInitializer([NotNull] JavaParserLabeled.ElementValueArrayInitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.annotationTypeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotationTypeDeclaration([NotNull] JavaParserLabeled.AnnotationTypeDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.annotationTypeBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotationTypeBody([NotNull] JavaParserLabeled.AnnotationTypeBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.annotationTypeElementDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotationTypeElementDeclaration([NotNull] JavaParserLabeled.AnnotationTypeElementDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>annotationTypeElementRest0</c>
	/// labeled alternative in <see cref="JavaParserLabeled.annotationTypeElementRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotationTypeElementRest0([NotNull] JavaParserLabeled.AnnotationTypeElementRest0Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>annotationTypeElementRest1</c>
	/// labeled alternative in <see cref="JavaParserLabeled.annotationTypeElementRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotationTypeElementRest1([NotNull] JavaParserLabeled.AnnotationTypeElementRest1Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>annotationTypeElementRest2</c>
	/// labeled alternative in <see cref="JavaParserLabeled.annotationTypeElementRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotationTypeElementRest2([NotNull] JavaParserLabeled.AnnotationTypeElementRest2Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>annotationTypeElementRest3</c>
	/// labeled alternative in <see cref="JavaParserLabeled.annotationTypeElementRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotationTypeElementRest3([NotNull] JavaParserLabeled.AnnotationTypeElementRest3Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>annotationTypeElementRest4</c>
	/// labeled alternative in <see cref="JavaParserLabeled.annotationTypeElementRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotationTypeElementRest4([NotNull] JavaParserLabeled.AnnotationTypeElementRest4Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>annotationMethodOrConstantRest0</c>
	/// labeled alternative in <see cref="JavaParserLabeled.annotationMethodOrConstantRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotationMethodOrConstantRest0([NotNull] JavaParserLabeled.AnnotationMethodOrConstantRest0Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>annotationMethodOrConstantRest1</c>
	/// labeled alternative in <see cref="JavaParserLabeled.annotationMethodOrConstantRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotationMethodOrConstantRest1([NotNull] JavaParserLabeled.AnnotationMethodOrConstantRest1Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.annotationMethodRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotationMethodRest([NotNull] JavaParserLabeled.AnnotationMethodRestContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.annotationConstantRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotationConstantRest([NotNull] JavaParserLabeled.AnnotationConstantRestContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.defaultValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefaultValue([NotNull] JavaParserLabeled.DefaultValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] JavaParserLabeled.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>blockStatement0</c>
	/// labeled alternative in <see cref="JavaParserLabeled.blockStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockStatement0([NotNull] JavaParserLabeled.BlockStatement0Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>blockStatement1</c>
	/// labeled alternative in <see cref="JavaParserLabeled.blockStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockStatement1([NotNull] JavaParserLabeled.BlockStatement1Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>blockStatement2</c>
	/// labeled alternative in <see cref="JavaParserLabeled.blockStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockStatement2([NotNull] JavaParserLabeled.BlockStatement2Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.localVariableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocalVariableDeclaration([NotNull] JavaParserLabeled.LocalVariableDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.localTypeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocalTypeDeclaration([NotNull] JavaParserLabeled.LocalTypeDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>statement0</c>
	/// labeled alternative in <see cref="JavaParserLabeled.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement0([NotNull] JavaParserLabeled.Statement0Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>statement1</c>
	/// labeled alternative in <see cref="JavaParserLabeled.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement1([NotNull] JavaParserLabeled.Statement1Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>statement2</c>
	/// labeled alternative in <see cref="JavaParserLabeled.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement2([NotNull] JavaParserLabeled.Statement2Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>statement3</c>
	/// labeled alternative in <see cref="JavaParserLabeled.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement3([NotNull] JavaParserLabeled.Statement3Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>statement4</c>
	/// labeled alternative in <see cref="JavaParserLabeled.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement4([NotNull] JavaParserLabeled.Statement4Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>statement5</c>
	/// labeled alternative in <see cref="JavaParserLabeled.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement5([NotNull] JavaParserLabeled.Statement5Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>statement6</c>
	/// labeled alternative in <see cref="JavaParserLabeled.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement6([NotNull] JavaParserLabeled.Statement6Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>statement7</c>
	/// labeled alternative in <see cref="JavaParserLabeled.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement7([NotNull] JavaParserLabeled.Statement7Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>statement8</c>
	/// labeled alternative in <see cref="JavaParserLabeled.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement8([NotNull] JavaParserLabeled.Statement8Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>statement9</c>
	/// labeled alternative in <see cref="JavaParserLabeled.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement9([NotNull] JavaParserLabeled.Statement9Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>statement10</c>
	/// labeled alternative in <see cref="JavaParserLabeled.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement10([NotNull] JavaParserLabeled.Statement10Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>statement11</c>
	/// labeled alternative in <see cref="JavaParserLabeled.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement11([NotNull] JavaParserLabeled.Statement11Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>statement12</c>
	/// labeled alternative in <see cref="JavaParserLabeled.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement12([NotNull] JavaParserLabeled.Statement12Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>statement13</c>
	/// labeled alternative in <see cref="JavaParserLabeled.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement13([NotNull] JavaParserLabeled.Statement13Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>statement14</c>
	/// labeled alternative in <see cref="JavaParserLabeled.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement14([NotNull] JavaParserLabeled.Statement14Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>statement15</c>
	/// labeled alternative in <see cref="JavaParserLabeled.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement15([NotNull] JavaParserLabeled.Statement15Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>statement16</c>
	/// labeled alternative in <see cref="JavaParserLabeled.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement16([NotNull] JavaParserLabeled.Statement16Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.catchClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCatchClause([NotNull] JavaParserLabeled.CatchClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.catchType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCatchType([NotNull] JavaParserLabeled.CatchTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.finallyBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFinallyBlock([NotNull] JavaParserLabeled.FinallyBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.resourceSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitResourceSpecification([NotNull] JavaParserLabeled.ResourceSpecificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.resources"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitResources([NotNull] JavaParserLabeled.ResourcesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.resource"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitResource([NotNull] JavaParserLabeled.ResourceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.switchBlockStatementGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitchBlockStatementGroup([NotNull] JavaParserLabeled.SwitchBlockStatementGroupContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.switchLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitchLabel([NotNull] JavaParserLabeled.SwitchLabelContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>forControl0</c>
	/// labeled alternative in <see cref="JavaParserLabeled.forControl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForControl0([NotNull] JavaParserLabeled.ForControl0Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>forControl1</c>
	/// labeled alternative in <see cref="JavaParserLabeled.forControl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForControl1([NotNull] JavaParserLabeled.ForControl1Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>forInit0</c>
	/// labeled alternative in <see cref="JavaParserLabeled.forInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForInit0([NotNull] JavaParserLabeled.ForInit0Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>forInit1</c>
	/// labeled alternative in <see cref="JavaParserLabeled.forInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForInit1([NotNull] JavaParserLabeled.ForInit1Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.enhancedForControl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnhancedForControl([NotNull] JavaParserLabeled.EnhancedForControlContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.parExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParExpression([NotNull] JavaParserLabeled.ParExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.expressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionList([NotNull] JavaParserLabeled.ExpressionListContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>methodCall0</c>
	/// labeled alternative in <see cref="JavaParserLabeled.methodCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodCall0([NotNull] JavaParserLabeled.MethodCall0Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>methodCall1</c>
	/// labeled alternative in <see cref="JavaParserLabeled.methodCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodCall1([NotNull] JavaParserLabeled.MethodCall1Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>methodCall2</c>
	/// labeled alternative in <see cref="JavaParserLabeled.methodCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodCall2([NotNull] JavaParserLabeled.MethodCall2Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expression8</c>
	/// labeled alternative in <see cref="JavaParserLabeled.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression8([NotNull] JavaParserLabeled.Expression8Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expression10</c>
	/// labeled alternative in <see cref="JavaParserLabeled.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression10([NotNull] JavaParserLabeled.Expression10Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expression9</c>
	/// labeled alternative in <see cref="JavaParserLabeled.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression9([NotNull] JavaParserLabeled.Expression9Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expression12</c>
	/// labeled alternative in <see cref="JavaParserLabeled.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression12([NotNull] JavaParserLabeled.Expression12Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expression11</c>
	/// labeled alternative in <see cref="JavaParserLabeled.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression11([NotNull] JavaParserLabeled.Expression11Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expression14</c>
	/// labeled alternative in <see cref="JavaParserLabeled.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression14([NotNull] JavaParserLabeled.Expression14Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expression13</c>
	/// labeled alternative in <see cref="JavaParserLabeled.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression13([NotNull] JavaParserLabeled.Expression13Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expression16</c>
	/// labeled alternative in <see cref="JavaParserLabeled.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression16([NotNull] JavaParserLabeled.Expression16Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expression15</c>
	/// labeled alternative in <see cref="JavaParserLabeled.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression15([NotNull] JavaParserLabeled.Expression15Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expression18</c>
	/// labeled alternative in <see cref="JavaParserLabeled.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression18([NotNull] JavaParserLabeled.Expression18Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expression17</c>
	/// labeled alternative in <see cref="JavaParserLabeled.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression17([NotNull] JavaParserLabeled.Expression17Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expression19</c>
	/// labeled alternative in <see cref="JavaParserLabeled.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression19([NotNull] JavaParserLabeled.Expression19Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expression6</c>
	/// labeled alternative in <see cref="JavaParserLabeled.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression6([NotNull] JavaParserLabeled.Expression6Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expression7</c>
	/// labeled alternative in <see cref="JavaParserLabeled.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression7([NotNull] JavaParserLabeled.Expression7Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expression4</c>
	/// labeled alternative in <see cref="JavaParserLabeled.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression4([NotNull] JavaParserLabeled.Expression4Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expression5</c>
	/// labeled alternative in <see cref="JavaParserLabeled.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression5([NotNull] JavaParserLabeled.Expression5Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expression2</c>
	/// labeled alternative in <see cref="JavaParserLabeled.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression2([NotNull] JavaParserLabeled.Expression2Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expression3</c>
	/// labeled alternative in <see cref="JavaParserLabeled.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression3([NotNull] JavaParserLabeled.Expression3Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expression0</c>
	/// labeled alternative in <see cref="JavaParserLabeled.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression0([NotNull] JavaParserLabeled.Expression0Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expression1</c>
	/// labeled alternative in <see cref="JavaParserLabeled.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression1([NotNull] JavaParserLabeled.Expression1Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expression21</c>
	/// labeled alternative in <see cref="JavaParserLabeled.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression21([NotNull] JavaParserLabeled.Expression21Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expression20</c>
	/// labeled alternative in <see cref="JavaParserLabeled.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression20([NotNull] JavaParserLabeled.Expression20Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expression23</c>
	/// labeled alternative in <see cref="JavaParserLabeled.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression23([NotNull] JavaParserLabeled.Expression23Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expression22</c>
	/// labeled alternative in <see cref="JavaParserLabeled.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression22([NotNull] JavaParserLabeled.Expression22Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expression25</c>
	/// labeled alternative in <see cref="JavaParserLabeled.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression25([NotNull] JavaParserLabeled.Expression25Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expression24</c>
	/// labeled alternative in <see cref="JavaParserLabeled.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression24([NotNull] JavaParserLabeled.Expression24Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.lambdaExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambdaExpression([NotNull] JavaParserLabeled.LambdaExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>lambdaParameters0</c>
	/// labeled alternative in <see cref="JavaParserLabeled.lambdaParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambdaParameters0([NotNull] JavaParserLabeled.LambdaParameters0Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>lambdaParameters1</c>
	/// labeled alternative in <see cref="JavaParserLabeled.lambdaParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambdaParameters1([NotNull] JavaParserLabeled.LambdaParameters1Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>lambdaParameters2</c>
	/// labeled alternative in <see cref="JavaParserLabeled.lambdaParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambdaParameters2([NotNull] JavaParserLabeled.LambdaParameters2Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>lambdaBody0</c>
	/// labeled alternative in <see cref="JavaParserLabeled.lambdaBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambdaBody0([NotNull] JavaParserLabeled.LambdaBody0Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>lambdaBody1</c>
	/// labeled alternative in <see cref="JavaParserLabeled.lambdaBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambdaBody1([NotNull] JavaParserLabeled.LambdaBody1Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>primary0</c>
	/// labeled alternative in <see cref="JavaParserLabeled.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimary0([NotNull] JavaParserLabeled.Primary0Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>primary1</c>
	/// labeled alternative in <see cref="JavaParserLabeled.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimary1([NotNull] JavaParserLabeled.Primary1Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>primary2</c>
	/// labeled alternative in <see cref="JavaParserLabeled.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimary2([NotNull] JavaParserLabeled.Primary2Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>primary3</c>
	/// labeled alternative in <see cref="JavaParserLabeled.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimary3([NotNull] JavaParserLabeled.Primary3Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>primary4</c>
	/// labeled alternative in <see cref="JavaParserLabeled.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimary4([NotNull] JavaParserLabeled.Primary4Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>primary5</c>
	/// labeled alternative in <see cref="JavaParserLabeled.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimary5([NotNull] JavaParserLabeled.Primary5Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>primary6</c>
	/// labeled alternative in <see cref="JavaParserLabeled.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimary6([NotNull] JavaParserLabeled.Primary6Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.classType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassType([NotNull] JavaParserLabeled.ClassTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>creator0</c>
	/// labeled alternative in <see cref="JavaParserLabeled.creator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreator0([NotNull] JavaParserLabeled.Creator0Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>creator1</c>
	/// labeled alternative in <see cref="JavaParserLabeled.creator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreator1([NotNull] JavaParserLabeled.Creator1Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>createdName0</c>
	/// labeled alternative in <see cref="JavaParserLabeled.createdName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreatedName0([NotNull] JavaParserLabeled.CreatedName0Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>createdName1</c>
	/// labeled alternative in <see cref="JavaParserLabeled.createdName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreatedName1([NotNull] JavaParserLabeled.CreatedName1Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.innerCreator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInnerCreator([NotNull] JavaParserLabeled.InnerCreatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.arrayCreatorRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayCreatorRest([NotNull] JavaParserLabeled.ArrayCreatorRestContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.classCreatorRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassCreatorRest([NotNull] JavaParserLabeled.ClassCreatorRestContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.explicitGenericInvocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExplicitGenericInvocation([NotNull] JavaParserLabeled.ExplicitGenericInvocationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.typeArgumentsOrDiamond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeArgumentsOrDiamond([NotNull] JavaParserLabeled.TypeArgumentsOrDiamondContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.nonWildcardTypeArgumentsOrDiamond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNonWildcardTypeArgumentsOrDiamond([NotNull] JavaParserLabeled.NonWildcardTypeArgumentsOrDiamondContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.nonWildcardTypeArguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNonWildcardTypeArguments([NotNull] JavaParserLabeled.NonWildcardTypeArgumentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.typeList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeList([NotNull] JavaParserLabeled.TypeListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.typeType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeType([NotNull] JavaParserLabeled.TypeTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.primitiveType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimitiveType([NotNull] JavaParserLabeled.PrimitiveTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.typeArguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeArguments([NotNull] JavaParserLabeled.TypeArgumentsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>superSuffix0</c>
	/// labeled alternative in <see cref="JavaParserLabeled.superSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSuperSuffix0([NotNull] JavaParserLabeled.SuperSuffix0Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>superSuffix1</c>
	/// labeled alternative in <see cref="JavaParserLabeled.superSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSuperSuffix1([NotNull] JavaParserLabeled.SuperSuffix1Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>explicitGenericInvocationSuffix0</c>
	/// labeled alternative in <see cref="JavaParserLabeled.explicitGenericInvocationSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExplicitGenericInvocationSuffix0([NotNull] JavaParserLabeled.ExplicitGenericInvocationSuffix0Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>explicitGenericInvocationSuffix1</c>
	/// labeled alternative in <see cref="JavaParserLabeled.explicitGenericInvocationSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExplicitGenericInvocationSuffix1([NotNull] JavaParserLabeled.ExplicitGenericInvocationSuffix1Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JavaParserLabeled.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArguments([NotNull] JavaParserLabeled.ArgumentsContext context);
}
} // namespace UndContain
